### ISSUE TITLE
Add Smart-TV Block and Adlists?

### ISSUE THREAD

**Issue by Perflyst** [WaLLy3K/wally3k.github.io#10]
Panasonic Viera: https://gist.github.com/Perflyst/529976b026eab571602aa7c1b253e6f0
Sony Bavaria: https://gist.github.com/Perflyst/2da7a1e7e12f3d76c8528e8a05896585
LG Smart-TV: https://gist.github.com/Perflyst/a7538478d0f6a764311dfe5bc40fbf8b

Useless connections from Smart-TV: https://gist.github.com/Perflyst/4e8b3786dcff0ffd5f017e1aba9fefe8

Your Samsung Smart-TV Blocklists + own added Domains: https://gist.github.com/Perflyst/315f86393712a0c2107ee8eb58c6acee (maybe check difference and add to yours)

**Comment by WaLLy3K** [comment]
Hey @Perflyst, that's a really valuable contribution you have there!

I'm tossing up whether to have one "Smart TV" list with all your domains, or add them under another category. I think the former would be better - do you have one gist that contains all of these which I can directly link to? 😄 

Thanks, and apologies for the delay in response.

**Comment by Perflyst** [comment]
Hey @WaLLy3K 

I once created a gist for you with all the domains I have.
You can find it here: https://gist.githubusercontent.com/Perflyst/4e68cfe7bb907dbeaec8641a82d002bf/raw/287d5b59d5e4b02b3f01d21850ffd764c98b7f4d/Smart-TV%2520Blocklist%2520Adlist%2520(for%2520PiHole)

**Comment by WaLLy3K** [comment]
That's great! Is it possible for you to put that on a repo, or somewhere where you can update the content while using the same URL? [As I've learnt](https://github.com/WaLLy3K/wally3k.github.io/pull/12), GitHub gist URL's don't point to the most current revision when the content has been updated and I'd like to point people to a non-static list!

**Comment by Perflyst** [comment]
Yes, no problem, i opened a repo.
You can find the list now here: https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt

**Comment by WaLLy3K** [comment]
To be fair, I should have asked for a repo link the first time and not a gist - so apologies for the change in mind!

Done and dusted, thank you *very* much! :grinning:
