### ISSUE TITLE
https://raw.githubusercontent.com/InnoScorpio/W3C_annual_most_used_survey_blocklist/master/Top500_Domains.txt looks dead

### ISSUE THREAD

**Issue by zappe** [WaLLy3K/wally3k.github.io#101]
This list is 404.

**Comment by nefty1029** [comment]
I decided to fork from Kees1958 W3C_annual_most_used_survey_blocklist myself and converted it into a domain list:
https://github.com/nefty1029/W3C_annual_most_used_survey_blocklist/blob/master/Top500%20Domain%20List.txt

By the way, does anyone have the backup to InnoScorpion's Domain List? I want to check if my converted file is in parity with his.

**Comment by nefty1029** [comment]
For those trying to add the list to their Pi-Hole, use this instead:
https://raw.githubusercontent.com/nefty1029/W3C_annual_most_used_survey_blocklist/master/Top500%20Domain%20List.txt

**Comment by ACMEd** [comment]
@nefty1029 Check the comments under [this commit](https://github.com/WaLLy3K/wally3k.github.io/commit/2fc3551505f5df4fc86dec2e4931d15e643ce21f). There's also a snapshot of the list _before_ these changes were made [here](https://web.archive.org/web/20200511231552/https://raw.githubusercontent.com/InnoScorpio/W3C_annual_most_used_survey_blocklist/master/Top500_Domains.txt).

Since the list is just supposed to be a "minimal" blocklist anyways, it's probably better to get the few non-duplicate domains on a "big" blocklist (like Peter Lowe's).

**Comment by beerisgood** [comment]
I doesn't make sense to fork a list but not having the maintenance power.

It exist a reason why the list got deleted by author

**Comment by nefty1029** [comment]
> 
> 
> @nefty1029 Check the comments under [this commit](https://github.com/WaLLy3K/wally3k.github.io/commit/2fc3551505f5df4fc86dec2e4931d15e643ce21f). There's also a snapshot of the list _before_ these changes were made [here](https://web.archive.org/web/20200511231552/https://raw.githubusercontent.com/InnoScorpio/W3C_annual_most_used_survey_blocklist/master/Top500_Domains.txt).
> 
> Since the list is just supposed to be a "minimal" blocklist anyways, it's probably better to get the non-duplicate domains on a "big" blocklist (like Peter Lowe's).

Thanks for the links, I was able to make some changes to the domain list.

**Comment by ACMEd** [comment]
I think I agree with @beerisgood. As I look at the list more, I find more domains that shouldn't be blocked, such as `dailymotion.com` and `t.co`. The original author removed the domains list for a reason: it's better off as a uBo filter list, not a hosts file.

**Comment by WaLLy3K** [comment]
With the [comments here](https://github.com/WaLLy3K/wally3k.github.io/commit/2fc3551505f5df4fc86dec2e4931d15e643ce21f) brought to my attention, and the discussion in this thread, I think it's a fair call to remove it.

Thank you for all your input - it would be infinitely more harder to keep up the quality without this help! :)
