### ISSUE TITLE
https://hostsfile.org/Downloads/hosts.txt - Outdated

### ISSUE THREAD

**Issue by zappe** [WaLLy3K/wally3k.github.io#104]
This list is no longer maintained. Last update is 2 years ago.

For example it has zopim.com as a false positive.

**Comment by WaLLy3K** [comment]
Yeah, I think two years is definitely a fair cutoff of "this list is never getting updated again" and can just outright be removed.

What do you think, @zappe and @beerisgood?

**Comment by beerisgood** [comment]
Even short time not updating a hosts file is enough and can produce big problems and 2 years is a lot to much so I vote for removing it.

It exist enough other projects
