### ISSUE TITLE
hosts/Airelle-trc.txt blocks...usenix??

### ISSUE THREAD

**Issue by nimbius** [WaLLy3K/wally3k.github.io#105]
www.usenix.org is blocked in the  https://v.firebog.net/hosts/Airelle-trc.txt but the maintainer is french and im extremely american and dont speak any french.  how do i go about fixing the problem where one of your maintainers has accidentally blocked one of the longest standing and most respected unix groups on the planet?

**Comment by WaLLy3K** [comment]
Hi @nimbius! I would honestly recommend *not* using Airelle's lists (as has been signified by it being marked as X). While you can get in contact and they do speak English, this maintainer is extremely inconsistent with their responsiveness and the list contains too many false positives.
