### ISSUE TITLE
gitlab.io Domain is blocked in Iran.

### ISSUE THREAD

**Issue by ahbanavi** [WaLLy3K/wally3k.github.io#106]
Hi, this address (https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser) is block in Iran.
can you use this address instead?
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/hosts_browser

I'm using automation script and fetch list automatically and each time i have to replace this address.

Thank you in advance.

![Here's a screenshot of problem](https://user-images.githubusercontent.com/39927312/82388501-04180b80-9a4f-11ea-9770-c5ad5519e45c.png)

**Comment by WaLLy3K** [comment]
Hi @ahbanavi! I can definitely understand where you're coming from, though I need to explain why I would strongly prefer to keep it as it is.

`gitlab.io`/`github.io` expose something known as the [Last Modified header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) which is used by Pi-hole to determine if the remote list is different to the local list, without having to first download the entire contents of the file. "Raw" URLs provided by GitHub and GitLab don't provide this, and cause Pi-hole to constantly redownload the latest version, even if nothing has changed.

(On a more technical note: Unfortunately `curl`, and therefore by extension, Pi-hole, doesn't have the ability to compare `etag`. If it did, I'd have no issue with catering to your request!)

Obviously it would be a huge benefit to you in the first place if you could get the list in the first place considering the country's firewall restrictions, but my only concern is that I believe the change would negatively impact more people than it would help.

I wish I could provide an answer that would solve the issue for you, sorry. Please let me know if there's anything else I might be able to assist with.

**Comment by ahbanavi** [comment]
There's no actual problem here. currently I add raw address of that one link manually and everything works fine.

> considering the country's firewall restrictions 

BTW I don't think Iran blocks gitlab.io, It's more like they have block Iran in the first place.

Thank you for your response.

**Comment by WaLLy3K** [comment]
> There's no actual problem here. currently I add raw address of that one link manually and everything works fine.

Fair enough. Hopefully you can find a way to automate this in the future, now that you have a firm answer.

> BTW I don't think Iran blocks gitlab.io, It's more like they have block Iran in the first place.

Ah, that would make more sense! :)
