### ISSUE TITLE
Consider removing adblock.mahakala.is entirely

### ISSUE THREAD

**Issue by irlittz** [WaLLy3K/wally3k.github.io#107]
I am aware that Mahakala is only in the "suspicious" lists (and therefore in the "All lists" set) and that I should expect to have to whitelist some sites myself, but some of the choices Mahakala makes are completely unreasonable.

By the looks of it it blocks all legit Amazon domains. When inspecting the list further after getting multiple false positives only from this list, it seems to include also almost all porn sites? even though it's not indicated as such (unless you consider all pornography to be inherently suspicious).

Compared to the other lists on Firebog, this one just doesn't seem very well maintained or thought out, and I don't feel like it belongs in the same category as the others.

**Comment by WaLLy3K** [comment]
From the reading points:
> Lists bulleted with a cross block multiple useful sites (e.g: Pi-hole updates, Amazon, Netflix)

While I'm aware the cross is quite small and can easily be overlooked, it *is* marked with an X to the left of the padlock which tells people I'm aware of this list and that I've crossed it off for poor quality.

I'm thinking I should do a CSS strikethrough to visually assist with recognising that it's not a list that lends itself towards quality. :)

**Comment by WaLLy3K** [comment]
Considering this issue further, I've made some extra changes this evening that'll make it easier to digest at a glance: ticked lists are green, non crossed links are hyperlink blue, and HTTP links are red... not that I expect to see any HTTP links added in the future!

If there's anything else I can help with @irlittz, please let me know!

**Comment by irlittz** [comment]
Thanks for the quick feedback and changes. It was really my fault for not reading your site properly -- thanks for making this more obvious.

**Comment by WaLLy3K** [comment]
No worries at all, and thank you for raising the issue - input like this helps me make the site more usable for everybody!
