### ISSUE TITLE
settings-win.data.microsoft.com

### ISSUE THREAD

**Issue by xxcriticxx** [WaLLy3K/wally3k.github.io#108]
false positive?
```
Match found in https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt:
   db5.settings-win.data.microsoft.com.akadns.net 
   db5-eap.settings-win.data.microsoft.com.akadns.net 
   geo.settings-win.data.microsoft.com.akadns.net 

 Match found in https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt:
   settingsfd-geo.trafficmanager.net 
```

![Capture](https://user-images.githubusercontent.com/15007183/82751981-0c42b480-9d89-11ea-9376-1234fe2f740c.PNG)

this was fixed before:
https://github.com/StevenBlack/hosts/issues/1114

**Comment by xxcriticxx** [comment]
cc @beerisgood

**Comment by WaLLy3K** [comment]
Hey @xxcriticxx, thanks for pointing this out! If you could lodge a ticket over on @crazy-max's [WindowsSpyBlocker repo](https://github.com/crazy-max/WindowsSpyBlocker/issues), it should hopefully be resolved quickly because I definitely don't think Microsoft Defender Advanced Threat Protection should be blocked.

**Comment by xxcriticxx** [comment]
ok i will open ticket on his/her's repo

**Comment by beerisgood** [comment]
Yeah this is a false positive and thankfully StevenBlack / someonewhocares.org fix this.

Let's see how the WindowsSpyBlocker handle that.

Thanks @xxcriticxx for ping me.

**Comment by WaLLy3K** [comment]
https://github.com/crazy-max/WindowsSpyBlocker/issues/224#issuecomment-650396820
> @p1r473 `settings-win.data.microsoft.com` is already in the [extra rules](https://github.com/crazy-max/WindowsSpyBlocker/blob/f82e395849947cc3913037d82e8f97fbedcbf920/data/hosts/extra.txt#L187).

Not sure what to make of that response.

**Comment by crazy-max** [comment]
@WaLLy3K 

> If their extra rules is a whitelist file

Extra rules are a bit of a catch-all and may impact certain services and third party applications like Skype, Bing, Live, Outlook, NCSI, Microsoft Office.
