### ISSUE TITLE
Remove DShield Domain Lists

### ISSUE THREAD

**Issue by AndrewDaws** [WaLLy3K/wally3k.github.io#110]
All three of the DShield lists have been officially suspended as per their post earlier today.

https://www.dshield.org/forums/diary/Suspending+Suspicious+Domain+Feed+Update+to+Researcher+IP+Feed/26204/

So the three domain lists linked should probably be marked off or removed for the foreseeable future.

https://www.dshield.org/feeds/suspiciousdomains_Low.txt
https://www.dshield.org/feeds/suspiciousdomains_Medium.txt
https://www.dshield.org/feeds/suspiciousdomains_High.txt

**Comment by llacb47** [comment]
Why crossed out? They don't contain any domains, they should be removed.

**Comment by AndrewDaws** [comment]
> Why crossed out? They don't contain any domains, they should be removed.

The should just be cross out for now in my opinion since they specifically said they were not maintaining until they find new feeds.

> .... I decided to no longer maintain the feed until we find new inputs. 

If they end up not adding any new feeds and updating after some amount of time (a few months?), then yes, it would definitely make sense to remove them, but for now it is probably best just to leave them noted as a potential source (should they update), rather than being forgotten entirely.

**Comment by WaLLy3K** [comment]
Closed as PR #111 has been merged.
