### ISSUE TITLE
Please unlist osint.bambenekconsulting.com

### ISSUE THREAD

**Issue by bambenek** [WaLLy3K/wally3k.github.io#112]
This is in Airelle-hrsk.txt. All this site does is provide feeds of malicious domains in text files. Not sure why it is listed.

**Comment by llacb47** [comment]
`Airelle-hrsk` is crossed through with an X **for a reason**.

**Comment by WaLLy3K** [comment]
To be fair, it used to be listed as a tick list! So to OP, I would strongly urge you update your blocklists and start by removing this one :)

**Comment by lightswitch05** [comment]
I was the one that told him it was blocked. I guess if the answer is “don’t use the list” then I will not use it.

**Comment by WaLLy3K** [comment]
I’m honestly not sure how Airelle sources their blocklists, and with some of the things I’ve seen blocked combined with their overall unresponsiveness, it’s just become a matter of “please don’t use!” 🙂
