### ISSUE TITLE
 i.imgur.com

### ISSUE THREAD

**Issue by xxcriticxx** [WaLLy3K/wally3k.github.io#114]
false positive?

Match found in https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt:
   i.imgur.com 

this breaks imgur.com main page

**Comment by xxcriticxx** [comment]
someone already posted on reddit

https://www.reddit.com/r/pihole/comments/h8lbpt/imgur_is_being_blocked_by_the_list/

**Comment by beerisgood** [comment]
Yes. It's needed for imgur.
I already wrote the guys a mail and i don't think that the PiHole guys can or will change here anything

**Comment by ACMEd** [comment]
This issue has been resolved over at davidonzo/Threat-Intel#9

Wally3k has no control over the contents of block lists, so opening an issue on this repo is futile. In the future, contact the maintainer of the list directly.
