### ISSUE TITLE
AdguardDNS.txt maintainer - entry removal

### ISSUE THREAD

**Issue by otisg** [WaLLy3K/wally3k.github.io#115]
I am unable to find the https://v.firebog.net/hosts/AdguardDNS.txt maintainer.  A few people reported not being able to see our blog posts (e.g. https://sematext.com/blog/linux-logs/ ) and it turned out we are somehow blocked.  I found our domain - sematext.com - listed in https://v.firebog.net/hosts/AdguardDNS.txt .  I am not really sure why we are there.  I did find a few other companies in our space (e.g., datadog and newrelic), but they don't have their whole domain blocked.  Would it be possible to remove sematext.com from there?  If we need to be blocked for some reason, could that entry at least be changed to a more specific hostname?  Maybe somebody wanted to block cdn.sematext.com that served our Real User Monitoring beacon?
Your help would be greatly appreciated.

**Comment by ACMEd** [comment]
Select “Toggle list maintainers” on https://firebog.net.

This list is by AdGuard. Open an issue over at https://github.com/AdguardTeam/AdguardSDNSFilter

**Comment by llacb47** [comment]
The list  `v.firebog.net/hosts/AdguardDNS.txt` is not maintained by Adguard. 

`sematext.com` is listed here: https://github.com/AdguardTeam/AdguardFilters/blob/2a3ba7a123c79c097abc395d32256796688b3663/SpywareFilter/sections/tracking_servers.txt#L2432

**Comment by ACMEd** [comment]
> The list `v.firebog.net/hosts/AdguardDNS.txt` is not maintained by Adguard.

I’m confused. What makes you believe it’s not by AdGuard?

**Comment by llacb47** [comment]
> > The list `v.firebog.net/hosts/AdguardDNS.txt` is not maintained by Adguard.
> 
> I’m confused. What makes you believe it’s not by AdGuard?

https://github.com/WaLLy3K/wally3k.github.io/issues/94#issuecomment-612273823

**Comment by WaLLy3K** [comment]
Thanks for the input, everyone! I will have to strip out any results matching `third-party` which have always been included when auto-parsing the upstream list.

Leave it with me, I should have time to sort this within 24 hours. 🙂

**Comment by otisg** [comment]
Glad I was able to surface a bug/improvement :)

**Comment by ACMEd** [comment]
This list https://filters.adtidy.org/extension/chromium/filters/15.txt (which is the same as (this list)[https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/Filters/rules.txt]) does not use the third-party qualifier.

**Comment by llacb47** [comment]
> Glad I was able to surface a bug/improvement :)
> And thanks for pointing me in the right direction! I opened [AdguardTeam/AdGuardSDNSFilter#366](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/366)

@otisg You should probably open the issue in https://github.com/AdguardTeam/AdguardFilters

**Comment by llacb47** [comment]
> The list on Firebog [filters.adtidy.org/extension/chromium/filters/15.txt](https://filters.adtidy.org/extension/chromium/filters/15.txt) (which is the same as this list [AdguardTeam/AdGuardSDNSFilter:Filters/rules.txt@`master`](https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/Filters/rules.txt?rgh-link-date=2020-06-16T01%3A56%3A03Z)) does not use the third-party qualifier.

`sematext.com` is not listed in https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/Filters/rules.txt

**Comment by ACMEd** [comment]
> sematext.com is not listed in https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/Filters/rules.txt

Oh, I see. But it _is_ listed on https://filters.adtidy.org/extension/chromium/filters/15.txt without the third-party qualifier. Where is the repo for that?

**Comment by ACMEd** [comment]
It’s listed on https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt. That link is on the readme for AdGuardTeam/AdGuardSDNSFilter which is why I was confused. What a mess.

**Comment by ACMEd** [comment]
- https://filters.adtidy.org/extension/chromium/filters/15.txt `||sematext.com^`
- https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt `||sematext.com^`
- https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/Filters/rules.txt `Not listed`
- https://github.com/AdguardTeam/AdguardFilters/blob/master/SpywareFilter/sections/tracking_servers.txt `||sematext.com^$third-party`

v.firebog.net pulls from the first one.

**Comment by llacb47** [comment]
The first one pulls from the fourth, so OP's issue report should probably go to https://github.com/AdguardTeam/AdguardFilters/.

**Comment by otisg** [comment]
Thanks!  AdGuard folks said it comes from EasyPrivacy, so I opened https://github.com/easylist/easylist/issues/5557

**Comment by WaLLy3K** [comment]
> Thanks for the input, everyone! I will have to strip out any results matching `third-party` which have always been included when auto-parsing the upstream list.

Based off a comment left by a previous me that I've long forgotten, `third-party` is definitely something that won't be parsed onto my lists [as per this tweet](https://twitter.com/filterpaper/status/1169916149338791936),

Since my parsed copy does indeed [use this URL as its source](https://filters.adtidy.org/extension/chromium/filters/15.txt), I'll wait for the above PR to get some headway before I can investigate further.

**Comment by otisg** [comment]
@WaLLy3K https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/366 got resolved. Does this help to move this issue forward?

**Comment by WaLLy3K** [comment]
> @WaLLy3K [AdguardTeam/AdGuardSDNSFilter#366](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/366) got resolved. Does this help to move this issue forward?

Looks like the list auto-updated itself (I think I've got it set to check every three days now instead of weekly), and I can't see `sematext.com` any more 😄
