### ISSUE TITLE
Prigent-Malware Blocking S3 in us-east-1

### ISSUE THREAD

**Issue by AjkayAlan** [WaLLy3K/wally3k.github.io#116]
Looks like https://v.firebog.net/hosts/Prigent-Malware.txt is blocking access to all AWS s3 buckets in us-east-1. Honestly this feels a bit aggressive to me, since many valid services use S3 in us-east-1.

Should this be removed from the list?

```
pi@raspberrypi:~ $ pihole -q -adlist -exact s3.us-east-1.amazonaws.com
 Exact match for s3.us-east-1.amazonaws.com found in:
  - https://v.firebog.net/hosts/Prigent-Malware.txt
```

**Comment by WaLLy3K** [comment]
That's definitely a giant red flag, to be blocking something as important as Amazon AWS. I've shot off a [whitelist request](https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi), and we'll see if that's removed in a timely fashion.

Hopefully it's removed by the following Sunday. If it's not, then I'll remove it from the ticklists.

**Comment by AjkayAlan** [comment]
Just following up, it looks like s3.us-east-1.amazonaws.com is still being blocked by https://v.firebog.net/hosts/Prigent-Malware.txt and is still on the ticklists.

**Comment by WaLLy3K** [comment]
I must have forgot to set a calendar entry to follow up on this, so thank you for the bump @AjkayAlan!

**Comment by ACMEd** [comment]
Update: `s3.us-east-1.amazonaws.com` has been removed from the list.

@WaLLy3K
