### ISSUE TITLE
EasyList doesn't block ads that it should.

### ISSUE THREAD

**Issue by MoonshineIndustries** [WaLLy3K/wally3k.github.io#117]
First question is, why does the easylist hosted by you differ than the original? 

In any case, the ads that are not blocked by pihole are on https://www.startpage.com/

[The original Easylist](https://easylist.to/easylist/easylist.txt) block them through the 
`?adtype=`
according to Ublock. Can you please fix, and also what about all the other similar rules?

**Comment by llacb47** [comment]
Do you understand how DNS blocking works?

**Comment by MoonshineIndustries** [comment]
Yeah, I didn't really look into it much. There's a way to do it with pihole using regex.

**Comment by llacb47** [comment]
Wrong, pihole can only see domain.

**Comment by MoonshineIndustries** [comment]
So what does that mean? Sites are immune from pihole if they run their ads through their own domain?

**Comment by llacb47** [comment]
Basically, that's why you should use uBlock Origin whenever possible for sites like amazon, youtube, etc. that run first-party ads.

**Comment by MoonshineIndustries** [comment]
Oh well, that's unfortunate. Thanks for the info.

**Comment by beerisgood** [comment]
Also solutions like PiHole get more and more useless as the sites already move from third party to first party which mean it's not possible with DNS as that would break the whole side.

See that as next step after CNAME which itself is a break for solutions like PiHole and never reach a end.

**Comment by MoonshineIndustries** [comment]
It's always a cat and mouse game with the big players. For the moment at least, most sites just use external domains and pihole is useful for, I dunno, about 70-80% of the ads.

Although I have noticed quite a bit more false-positives and app/site breaking rules in the default pihole adlists than in default ublock, some of the lists are not that well curated, it seems.

As for the future, I'm guessing pihole will evolve to more than just a DNS blocker, but something that actually inspect the sites like Ublock. But that's just a guess, I don't know their plans.
