### ISSUE TITLE
Keep the newest "ticked" blocklists

### ISSUE THREAD

**Issue by BulldozerPete** [WaLLy3K/wally3k.github.io#118]
Hallo,

I have added the "ticked" blocklists to my pihole. But when a list becomes "un-ticked" or a new one will be added, I have to manually check this.
Is there an option to have always the up to date "ticked" blocklists?

thx

**Comment by WaLLy3K** [comment]
@jacklul the absolute legend has a tool to do exactly this: https://github.com/jacklul/pihole-updatelists

For future reference, this link is found on my front page under the first reading points! :)
