### ISSUE TITLE
ghacks.net

### ISSUE THREAD

**Issue by xxcriticxx** [WaLLy3K/wally3k.github.io#119]
i think this list is catching ghacks.net

```
Match found in https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt:
   kinghacks.net 
```

**Comment by WaLLy3K** [comment]
The way Pi-hole works is if you do a query for `pihole -q a.net`, it will search for anything that has that string in the domain. If Pi-hole returns a positive result for `pihole -q -exact ghacks.net`, then *this* is when the domain will be blocked.

Hope that helps! :)

**Comment by ACMEd** [comment]
@xxcriticxx were you using hostsVN?
bigdargon/hostsVN#249
