### ISSUE TITLE
Airelle-trc blocklist blocking www.propublica.org

### ISSUE THREAD

**Issue by RooneyMcNibNug** [WaLLy3K/wally3k.github.io#120]
Hi there, 

I know that others have submitted seperate issues regarding false-positives in the Airelle blocklists - only to find that it is not well moderated - but I figured I would still report an issue regarding another URL being blocked in one of these lists just to have it on record.

The `airelle-trc` list (https://v.firebog.net/hosts/Airelle-trc.txt) is blocking `www.propublica.org`, which is a trusted news source. Let me know if there is any way that we can get it unblocked?

Thanks for all your work,
- Rooney

**Comment by llacb47** [comment]
The list is not ticked and crossed out for a reason. The maintainer does not respond to false positive reports.

**Comment by WaLLy3K** [comment]
Hey @RooneyMcNibNug! Honestly, there's pretty much nothing I can do about it. The cross is my "seal of disapproval" (so to speak), and I'd rather have a cross than not have any mention at all for anyone else who stumbles upon the list in their quests. :)
