### ISSUE TITLE
False positive - liveperson.com - shalla-mal.txt

### ISSUE THREAD

**Issue by zappe** [WaLLy3K/wally3k.github.io#121]
This is chat software

**Comment by WaLLy3K** [comment]
G'day @zappe, I'd recommend shooting a whitelist request through to [the list maintainer directly](http://www.shallalist.de/submissions.html). Let me know whether they reply in a timely manner, because that information is extremely helpful to know! :)

**Comment by zappe** [comment]
Thanks, I did!
Though it seems to be a bit abandoned, http://www.shallalist.de/cgi-bin/queuelist.cgi.
3 months and nothing happened.

By the way, did you have a page on your site with all maintainers?

**Comment by ACMEd** [comment]
@zappe 
> By the way, did you have a page on your site with all maintainers?

Select the “Toggle list maintainer sources” button on the website.

**Comment by WaLLy3K** [comment]
Looks like `www.liveperson.com` is still on that list despite the whitelist request. I'm strongly considering unticking this, if the lack of whitelisting continues.
