### ISSUE TITLE
BarbBlock has moved

### ISSUE THREAD

**Issue by ACMEd** [WaLLy3K/wally3k.github.io#123]
The BarbBlock list (which was previously held at `https://ssl.bblck.me/blacklists/hosts-file.txt`) is now at `https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt`

See paulgb/BarbBlock#34

**Comment by krystian3w** [comment]
#124

**Comment by WaLLy3K** [comment]
Resolved as per #124. thanks!
