### ISSUE TITLE
bad repo URL

### ISSUE THREAD

**Issue by unarj** [WaLLy3K/wally3k.github.io#126]
looks like something is being redacted here, https://v.firebog.net/hosts/lists.php?type=nocross has a repo listed as https://cdn.jsdelivr.net/gh/neoFelhz/[email&#160;protected]/basic/hosts

**Comment by WaLLy3K** [comment]
I've disabled Email Address Obfuscation through Cloudflare's Scrape Shield, since that was apparently detecting `neohosts@gh-pages` as an email address. All fixed now :)

**Comment by unarj** [comment]
while the issue is fixed in that the URL is properly displayed, thought you might want to know that PiHole still chokes on the @ symbol.  thanks for the quick response, cheers.
