### ISSUE TITLE
Reconsideration of Kees1958's Ad/Tracking Blocklist 

### ISSUE THREAD

**Issue by nefty1029** [WaLLy3K/wally3k.github.io#128]
Just yesterday, Kees1958 uploaded some of his filter lists in HOSTS format. 
Since it used to be in the guide, maybe it is possible to add it back again?

Since there are 2 filter list in his page right now, I would recommend the one named: "TOP_EU_US_Ads_Trackers_HOST".

https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/master/TOP_EU_US_Ads_Trackers_HOST

**Comment by dmginc** [comment]
URL should be the 'raw' domain:

https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/TOP_EU_US_Ads_Trackers_HOST

**Comment by beerisgood** [comment]
Thanks for adding our list!

@Kees1958
