### ISSUE TITLE
Please remove this list https://www.malwaredomainlist.com/hostslist/hosts.txt

### ISSUE THREAD

**Issue by quyentruong** [WaLLy3K/wally3k.github.io#129]
[https://www.malwaredomainlist.com/hostslist/hosts.txt](https://www.malwaredomainlist.com/hostslist/hosts.txt) is no longer active.

**Comment by dschaper** [comment]
From https://github.com/pi-hole/pi-hole/issues/3925

https://riskanalytics.com/community/

**Comment by WaLLy3K** [comment]
Thanks @quyentruong and @dschaper! 🙂
