### ISSUE TITLE
Add this list

### ISSUE THREAD

**Issue by yolofy** [WaLLy3K/wally3k.github.io#130]
https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist

**Comment by WaLLy3K** [comment]
Hey, thanks for opening a ticket!

I'll take a look at https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist#credits--thanks (the sources directly), but I won't add a consolidated list directly due to reasons outlined on the front page of the site :)
