### ISSUE TITLE
Phishtank list? 

### ISSUE THREAD

**Issue by tg12** [WaLLy3K/wally3k.github.io#132]
Hi, Just wondered if you were interested in using my phishing master list. 

https://raw.githubusercontent.com/tg12/pihole-phishtank-list/master/list/phish_domains.txt

I have taken inspiration from Phishtank.

I also collate that with a wider list of blocklists into one "ultimate" blocklists.

https://github.com/tg12/pihole-phishtank-list/blob/master/full_grav_list/gravity.txt

**Comment by WaLLy3K** [comment]
Thanks, added! 🙂

**Comment by pchristod** [comment]
Hi,

I've added that list just now because it was ticked. Imho it should be however (at least) unticked, I however instantly removed it. It seems to block several legitimate websites, few examples are:
www.google.com
hangouts.google.com
meet.google.com

Haven't looked for more.
