### ISSUE TITLE
KADhosts

### ISSUE THREAD

**Issue by pallebone** [WaLLy3K/wally3k.github.io#133]
Hello.

Firstly thank you for your firebog website. It is very useful and I make use of it 👍 

One thing I notices was this list near the top:
https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts_without_controversies.txt

contains no entries and it says in the list:
"KADhosts doesn't contain controversial sites now, so KADhosts_without_controversies is redundant"

The list it suggests to use is this:
https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt

Hope you can review and let me know your thoughts :)

Pete

**Comment by dangrussell** [comment]
Just submitted a PR ( #134 ) to fix this.

**Comment by pallebone** [comment]
Thank you.

**Comment by pallebone** [comment]
Issue resolved with PR 134
