### ISSUE TITLE
Phishtank list blocks www.google.com

### ISSUE THREAD

**Issue by simphide** [WaLLy3K/wally3k.github.io#135]
I will also inform the list owner

```
www.gonzalofaccastonelli.com
www.goodlookinteriors5.com
www.google.com
www.google.com.br
www.govuk-dvla.com
www.govuk-form.com
```

**Comment by simphide** [comment]
https://github.com/tg12/pihole-phishtank-list/issues/1

It seems to be on purpose in the list, so I would definitely recommend to cross the list at least

**Comment by gschmidl** [comment]
It also doesn't follow the format correctly:

```
[i] Received 5657 domains, 20 domains invalid!
      Sample of invalid domains:
      - 113.161.144.143:8082
      - 141.193.196.75:84
      - 34.228.53.85:80
      - 35.196.197.52:80
      - appleverificationalert.com:443
```

**Comment by pchristod** [comment]
Oh, didn't see there was an open issue. I too posted this in the Original Issue here https://github.com/WaLLy3K/wally3k.github.io/issues/132
Also hangouts.google.com and meets.google.com are blocked. I've removed this list entirely after 5 minutes.

**Comment by WaLLy3K** [comment]
I'm genuinely surprised that Phishtank's lists have these issues, and what's worse is that *I missed this* when adding it in. Thank you @simphide, @gschmidl, @pchristod - that's been removed now.
