### ISSUE TITLE
quidsup/notrack-blocklists unhandled false positive(s) and limited maintenance

### ISSUE THREAD

**Issue by dsvk** [WaLLy3K/wally3k.github.io#136]
Similar to #63 - I can confirm https://gitlab.com/quidsup/notrack-blocklists/-/issues/45 (`influxdata.com` - reported by another user, not myself) is indeed a false positive, the correct domain to block would have been `usage.influxdata.com` (which the ticked AdGuardDNS list already blocks). There has been no reply from the list maintainer for 3 weeks.

I also subsequently noticed a non-insignificant number of [other open false positive reports](https://gitlab.com/quidsup/notrack-blocklists/-/issues) by various users with no responses going back weeks to months.

Meanwhile the maintainer has stated [here](https://gitlab.com/quidsup/notrack-blocklists/-/issues/33#note_392796049) 6 months ago that they "have too many things to deal with to actively look at the issues in Gitlab". Considering this it might be appropriate to at least untick these lists.

**Comment by WaLLy3K** [comment]
> Meanwhile the maintainer has stated here 6 months ago that they "have too many things to deal with to actively look at the issues in Gitlab". Considering this it might be appropriate to at least untick these lists.

Life gets the better of all of us (goodness only knows the amount of time it takes me to check in on Github and respond to requests!), but at least his quote there is all the reasonable justification I need to untick the list.

Thanks for opening this issue, much appreciated!
