### ISSUE TITLE
False positive: f002.backblazeb2.com (Prigent Malware)

### ISSUE THREAD

**Issue by theincogtion** [WaLLy3K/wally3k.github.io#137]
Match found in https://v.firebog.net/hosts/Prigent-Malware.txt:
   f002.backblazeb2.com 

My backblaze B2 backups failed due to this list entry.

**Comment by WaLLy3K** [comment]
Thanks for bringing this up - I've submitted a whitelist request to https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi

For future reference, that page is found on [this site](https://dsi.ut-capitole.fr/blacklists/index_en.php), which is revealed on my collection when you click on "Toggle list maintainer sources" and scroll down for Prigents lists :)
