### ISSUE TITLE
Non-crossed list (yhosts) inside Suspicious list is unmaintained 

### ISSUE THREAD

**Issue by aphichat-w** [WaLLy3K/wally3k.github.io#138]
[This list](https://raw.githubusercontent.com/vokins/yhosts/master/hosts) has not been updated since 2020-April-18 according to [the owner](https://github.com/vokins/yhosts)    he pass the torch to [VeleSila](https://github.com/VeleSila/yhosts) who has been maintaining yhosts since then.

**Comment by WaLLy3K** [comment]
Thanks very much for the info @aphichat-w, that's been sorted now! 🙂
