### ISSUE TITLE
Easylist issue

### ISSUE THREAD

**Issue by zappe** [WaLLy3K/wally3k.github.io#139]
There seems to be an issue when you load the Easylist to your list.
It removes ^$popup which removes functionality.

For example shortpixel.ai is not an tracker, see https://github.com/easylist/easylist/issues/6340

**Comment by WaLLy3K** [comment]
Thanks for the link to that ticket, I've removed `popup` as an accepted "adblock type option" with my parser which now currently only includes `^$(important|subdocument|websocket)` 🙂
