### ISSUE TITLE
Untick Prigent Crypto

### ISSUE THREAD

**Issue by niklasea** [WaLLy3K/wally3k.github.io#141]
Prigent's cryptojacking list blocks popular and legitimate sites related to cryptocurrency, including sites that do not host mining pools (i.e. are in no way used for cryptojacking). Referencing your decision in issue https://github.com/WaLLy3K/wally3k.github.io/issues/72, I suggest unticking Prigent's cryptojacking list introduced in https://github.com/WaLLy3K/wally3k.github.io/commit/6ff95c538d9aa16d8d2c01d64709a92e3823c949. The two example sites from that issue (coinbase.com and bitcoin.de) are also blocked by Prigent's list.

**Comment by WaLLy3K** [comment]
I've submitted [a whitelist request](https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi) for your two examples, and I would recommend shooting any more false positives through to that request page. Fabrice is quite responsive via email too: `fabrice.prigent [at] ut-capitole.fr`.

If there are more examples you can mention that aren't actioned by Fabrice, please let me know and I'll be happy to review my recommendation for that list!
