### ISSUE TITLE
Remove Kees1958's top tracker list

### ISSUE THREAD

**Issue by ndrkmn** [WaLLy3K/wally3k.github.io#142]
The link is returning 404 error as the file was deleted from git https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/commit/953338a54ed8f405862fd7fcc91acb04c627aedd

I posted a comment on the commit, another person submitted an issue and so far there was no response.

**Comment by WaLLy3K** [comment]
Unfortunately, I often need to be pinged [elsewhere](https://firebog.net/about) because GitHub never sends me push notifications (iOS) when changes occur. Thanks for letting me know about the PR though, I saw this before I saw @Alyetama's work. 🙂

**Comment by Zelo72** [comment]
https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/issues/59#issuecomment-963921246

**Comment by WaLLy3K** [comment]
> [Kees1958/W3C_annual_most_used_survey_blocklist#59 (comment)](https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/issues/59#issuecomment-963921246)

Thanks for that, added! 🙂

**Comment by ilpianista** [comment]
@WaLLy3K FYI the list is gone :-(

**Comment by WaLLy3K** [comment]
Thanks very much for the @, I actually got a notification from the GitHub app on my phone about it for once (!!!) 😅
