### ISSUE TITLE
GeForce Experince

### ISSUE THREAD

**Issue by mattyteds** [WaLLy3K/wally3k.github.io#144]
Blocking ls.dtrace.nvidia.com prevents GeForce experience from checking for new drivers.

**Comment by dmginc** [comment]
Which list is does that domain appear in and/or did you bring it to the list maintainers attention?

**Comment by mattyteds** [comment]
> Which list is does that domain appear in
The WaLLy3K Personal Blocklist
https://v.firebog.net/hosts/static/w3kbl.txt

> and did you bring it to that list maintainers attention?
I thought that's what I was doing.

**Comment by dmginc** [comment]
Well without specifying which list it was in it was hard to read your mind :)

**Comment by mattyteds** [comment]
> Well without specifying which list it was in it was hard to read your mind :)

I wasn't aware people reported issues with other people's list here, I assumed they would do that on the maintainers github.

**Comment by mattyteds** [comment]
Appears it's not on this list. I must have misread my query log, or it was already removed.
