### ISSUE TITLE
https://v.firebog.net/hosts/Shalla-mal.txt 404's

### ISSUE THREAD

**Issue by ezek1el** [WaLLy3K/wally3k.github.io#146]
Apparently https://v.firebog.net/hosts/Shalla-mal.txt is missing.

**Comment by WaLLy3K** [comment]
It works for me, even in a private browser. I can't even imagine how that'd happen, because my auto-update script shouldn't even be deleting it first. Feel free to message me somewhere directly if this happens again, so I can look into it in a timely manner.

**Comment by unaRIpurpose** [comment]
Needs to be reopened? --- File referred by the Link (i.e. https://v.firebog.net/hosts/Shalla-mal.txt) not accesible !
![TEMP](https://user-images.githubusercontent.com/94373861/190406320-87d7e5ea-decb-4591-8b38-73427f6d1f8a.png)

**Comment by WaLLy3K** [comment]
This list is no longer supported by its maintainer (and hasn't been for quite a while), so I've discontinued mirroring it after I did a big update on my parsing/mirror script 🙂

I still have a copy of it if needed, but I wouldn't encourage its use

Cheers!

**Comment by unaRIpurpose** [comment]
okay .... <although> i am led to believe that the list was working fine during the recurrent gravity updates I was performin in the past 3-4 months but <\although> .... if you say its deprecated, I'd drop the reference of this list from My PiHoles' "Adlist" List

Thanks. :-)

![TEMP](https://user-images.githubusercontent.com/94373861/190551309-d6bae88e-501a-4eb5-9814-2de3c7e04c99.png)

**Comment by WaLLy3K** [comment]
You're absolutely right, it was a cached copy that had remained unchanged for quite. That's where the parser change came in - I cleaned out the folder and only have the currently recommended lists available.

It's definitely a more blunt (*and rare for me*) approach to just delete the existing cache, but I feel it's better for people who manually update their sources not to be using extremely stagnant lists.

Hope that better clarifies things, and please hit me up if you have any questions! 🙂

**Comment by unaRIpurpose** [comment]
Haha!
.
.
\<Subtext> Doesn't the spirit of "Backward Compatability" still discourage Deletes in Tech? <\Subtext> ;-)
