### ISSUE TITLE
Typeo in  https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt list

### ISSUE THREAD

**Issue by liamgibbins** [WaLLy3K/wally3k.github.io#149]
0.0.0.0aktywtylicz.pl

think there should be a space between the 0.0.0.0 aktywtylicz.pl

The rest of the lists look good to me.

Thank you for keeping the lists up todate, appreciate what your doing here.

**Comment by WaLLy3K** [comment]
Looks like this one was corrected by [the list maintainer](https://github.com/FiltersHeroes/KADhosts) already, which is good to see given how long ago you brought this up here 🙂
