### ISSUE TITLE
Lists no longer valid

### ISSUE THREAD

**Issue by stordoff** [WaLLy3K/wally3k.github.io#15]
> https://raw.githubusercontent.com/StevenBlack/hosts/master/data/SpotifyAds/hosts

This list is no longer valid as the StevenBlack repo has changed how it handles the Spotify domains (per https://github.com/StevenBlack/hosts/commit/6dd1a88e2e51dd0960a2c65436f61719109b1e36#diff-8d777f385d3dfec8815d20f7496026dc)

> https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt

~~SSL Certificate is currently invalid (2018-02-15, but certificate expired 2018-02-14). May be updated at some point.~~ Update: Site has a new SSL cert.

**Comment by WaLLy3K** [comment]
Thank you very much! 😄
