### ISSUE TITLE
store.steampowered.com

### ISSUE THREAD

**Issue by DeJkSEBA** [WaLLy3K/wally3k.github.io#151]
Official Steam store site (store.steampowered.com) blocked on https://v.firebog.net/hosts/Airelle-trc.txt

**Comment by WaLLy3K** [comment]
Please don't use that list - I've had to mark it as not recommended for use due to incessant false positives, so please make sure you're using [my current recommendations](https://v.firebog.net/hosts/lists.php).

Something blocking Steam, seriously? Ugh. 😞
