### ISSUE TITLE
remove clickhouse.com from llist.

### ISSUE THREAD

**Issue by redgloboli** [WaLLy3K/wally3k.github.io#152]
Hi,

could you remove clickhouse.com from your blacklist, please?

It was bought by an open source project ( https://github.com/ClickHouse/ClickHouse ) and doesn't serve ads anymore.

See:

https://github.com/StevenBlack/hosts/issues/1781

**Comment by WaLLy3K** [comment]
Hi, thanks for the message! Generally, I link directly to the source material unless it's hosted at `v.firebog.net` - they're just HOSTS format friendly mirrors of the original.

`clickhouse.com` is found in the following blocklists (on my Pi-hole install):

```
pihole -q clickhouse.com
 Match found in https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt:
   clickhouse.com
 Match found in https://v.firebog.net/hosts/Prigent-Ads.txt:
   clickhouse.com
 Match found in https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt:
   clickhouse.com
 Match found in https://v.firebog.net/hosts/Shalla-mal.txt:
   www.clickhouse.com
 Match found in https://someonewhocares.org/hosts/zero/hosts:
   ads.clickhouse.com
 Match found in https://winhelp2002.mvps.org/hosts.txt:
   www.clickhouse.com
```

The following domains can be found by clicking on the blue "Toggle list maintainer sources" link for each relevant list:
`info [at] disconnect.me` (Found [here](https://disconnect.me/about))
https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi
http://www.shalla.de/impressum.html
https://someonewhocares.org/hosts/ (Email in the comments at the top of the blocklist)
`winhelp2002 [at] gmail.com` (Found [here](https://winhelp2002.mvps.org/))

Contact them, and they'll hopefully respond in a timely manner. If some don't, shoot another comment through in this ticket - my recommendation of lists take into account how responsive they are to corrections.
