### ISSUE TITLE
Not Found Prigent-Adult.txt

### ISSUE THREAD

**Issue by xtreemrage** [WaLLy3K/wally3k.github.io#153]
Thanks for all your hard work, I noticed that I get the following message for the following url: https://v.firebog.net/hosts/Prigent-Adult.txt.
Somehow I can't get on the site of the maintainer anymore... 

> Not Found
> 
> The requested URL was not found on this server.

**Comment by xtreemrage** [comment]
Seems to be back!

**Comment by WaLLy3K** [comment]
Hi @xtreemrage, thanks for this. Hopefully it should be fixed as per the mention above!
