### ISSUE TITLE
New blocklists from curben.gitlab.io

### ISSUE THREAD

**Issue by nefty1029** [WaLLy3K/wally3k.github.io#154]
Hello Wally3k, I recently discovered that Curben added 3 new blocklists to his site.
Out of the 3, only 2 of them are compatible with Pi-Hole.

1. https://gitlab.com/curben/phishing-filter
File: https://curben.gitlab.io/malware-filter/phishing-filter-hosts.txt

2. https://gitlab.com/curben/pup-filter
File: https://curben.gitlab.io/malware-filter/pup-filter-domains.txt

Maybe they can be added to your list?

**Comment by WaLLy3K** [comment]
I honestly can't remember when I self assigned myself to this, or where the reminder to follow up on this went -- my apologies!

The silver lining is that it's given time for this repo to mature a bit, and for the final location to settle as the [phishing-filter-hosts.txt](https://curben.gitlab.io/malware-filter/phishing-filter-hosts.txt) link no longer works, but [this one](https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt) does.

While there's a decent overlap in results with [phishing.army's blocklist](https://phishing.army/download/phishing_army_blocklist_extended.txt), there are still results that don't appear here - and when it comes to phishing, there's a negligible risk of false positive.
