### ISSUE TITLE
Prigent-Adult list unavailable

### ISSUE THREAD

**Issue by ghost** [WaLLy3K/wally3k.github.io#155]
Hey @WaLLy3K,
first of all, a big thank-you for painstakingly maintaining your Big Blocklist Collection.
I've noticed that the list with the URL "https://v.firebog.net/hosts/Prigent-Adult.txt" has not been available for quite some time:

![grafik](https://user-images.githubusercontent.com/99537264/153709409-173d2447-d83d-4a92-9879-38becc6d34b7.png)

I'm using this list on my Pi-hole and thought I'd let you know that it's unavailable.

**Comment by WaLLy3K** [comment]
Thanks for the ping @zackiff51, and I now notice [it's been a bit hit or miss](https://github.com/WaLLy3K/wally3k.github.io/issues/153). I've just made a separate parser for that list (set to update once a week) which seems to let the script process the final 100mb text file successfully.

Please feel free to hit me up if it stops working as expected in the future 🙂

**Comment by zackiff51** [comment]
Thanks for the speedy reply and fix!

I will hit you up if it stops working again. :)

**Comment by ytoruec80** [comment]
Hey @WaLLy3K,
once again, the Prigent-Adult list is unavailable (404 Not Found).

**Comment by WaLLy3K** [comment]
Noted, and looking into it. Thanks @ytoruec80

**Comment by WaLLy3K** [comment]
While I've resolved it by manually running the script (after adding a few more debug lines), I haven't actually pinned down *where* the script fails. I've re-opened this with the knowledge that this is an ongoing issue and will likely reoccur in the future.

**Comment by ytoruec80** [comment]
Thanks a lot for the quick fix and the good work! :)

**Comment by nindilo51** [comment]
@WaLLy3K Unfortunately, it's happening again. :/

**Comment by WaLLy3K** [comment]
Thank you @nindilo51, I *think* I've pinned down the issue to PHP kicking up a stink trying to ensure every line is unique - which definitely isn't a check that's needed for this particular list.

The list is back up again now :)

**Comment by nindilo51** [comment]
Yep, it's back to normal now. Great work! :) 
Well, PHP is a _special_ programming language. :D

**Comment by mastermc0** [comment]
@WaLLy3K looks like it's missing again.

**Comment by WaLLy3K** [comment]
Getting closer to figuring this out; have got it back up for now.

**Comment by lyops57** [comment]
Hey @WaLLy3K,
the list is unavailable again.

**Comment by WaLLy3K** [comment]
The script processes everything, but fails to save everything at the end like it's running out of memory despite nothing showing up in PHP error logs, or looking at the server via `htop`. I've removed all line validation (which wasn't doing a whole lot according to the debug output) and that let the final output save on first attempt.

If I had another box available (that wasn't either self hosted or work hosted), I'd whip up the script in another non-trash language and we'd be fine. Unfortunately, this is the one 'cost' for hosting everything for free on a reliable and trustworthy box :)

**Comment by lyops57** [comment]
Either way, I really appreciate the effort you're putting into this. Thank you! :)

**Comment by codygp** [comment]
@WaLLy3K Its down again.

Are you looking for server hosting or something like that. I might be able to help. I have a server I pay for that I barely use.

**Comment by WaLLy3K** [comment]
Hey @codygp, thanks for letting me know, it's back up. I've got a server I can do the processing on, I've just never had the time AND drive to rewrite this from the ground up. I've got a week off from work, so I'll try to bang something out to fix this properly.

**Comment by WaLLy3K** [comment]
All done. Anything done with the new parser will have some comments up the top, and I'll get around to migrating everything over to it as it's *considerably* faster than what I had.

https://v.firebog.net/hosts/Prigent-Adult.txt

If there are any issues, please let me know.

**Comment by WaLLy3K** [comment]
Everything's been migrated to the new parser now, which can be seen at https://v.firebog.net/hosts
