### ISSUE TITLE
Remove from lists

### ISSUE THREAD

**Issue by in23o** [WaLLy3K/wally3k.github.io#156]
Hello!

could you remove henary . de from all blacklist, please?

The domain is good on all services:
i.e.: https://www.virustotal.com/gui/url/266eaa4c63171b354abfd5ab78e1e44348a9ef344fa4fb346284087a985623af?nocache=1

 There was probably a hack in December, which has long since been remedied by a server change and domain transfer.

Thank You!

**Comment by WaLLy3K** [comment]
I don't see `henary.de` in any of the lists, so fortunately I won't have to go around contacting the maintainer of each list 🙂

**Comment by in23o** [comment]
Thank you for your feedback.

Apparently the domain meanwhile was has been deleted from 
https://v.firebog.net/hosts/Prigent-Malware.txt
and 
https://v.firebog.net/hosts/Prigent-Phishing.txt
after all other directories had delisted it as well.
