### ISSUE TITLE
Mastodon false-positive.

### ISSUE THREAD

**Issue by dataprolet** [WaLLy3K/wally3k.github.io#157]
The domain `mstdn.social` is on the _Prigent-Malware_ list, but it's just a [Mastodon instance](https://mstdn.social/about). Please remove it.

**Comment by WaLLy3K** [comment]
You can find the maintainer of a list by clicking "Toggle list maintainer sources" which eventually brings you to the whitelist request page: https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi

I've gone ahead and submitted this one for you.
