### ISSUE TITLE
Please add this list.

### ISSUE THREAD

**Issue by fX4N1DmH311X39SpxXLWxMWy49n6o8zb** [WaLLy3K/wally3k.github.io#158]
Link to the project
https://github.com/complexorganizations/content-blocker

Link to the hosts file
https://raw.githubusercontent.com/complexorganizations/content-blocker/main/assets/hosts

Whats type of domains are in the list?
Advertisement, Tracking, Malware, Phishing

**Comment by WaLLy3K** [comment]
I'm going to have to decline adding this. While 323 extra domains could be quite valuable (quality over quantity, after all!), there's no information on how these domains are sourced (unless there's some deeper explanation to [this picture](https://raw.githubusercontent.com/complexorganizations/content-blocker/main/assets/content-blocker.png) that I'm missing) and the following domains I can recognise aren't covered by the Advertising/Tracking/Malware/Phishing categories:

```
unity3d.com
yahoo.net
yahoodns.net
zdassets.com
zimperium.com
```

I absolutely appreciate your request none the less, even though it's taken some time for me to get back to you 🙂
