### ISSUE TITLE
joewein.net list isn't accessible

### ISSUE THREAD

**Issue by Cauchon** [WaLLy3K/wally3k.github.io#16]
https://www.joewein.net/dl/bl/dom-bl-base.txt

> Forbidden
> You don't have permission to access /dl/bl/dom-bl-base.txt on this server.

**Comment by mayesidevel** [comment]
I've been getting this for a few days as well. I suspected that it was due to [their policy on downloading that particular list](https://www.joewein.net/spam/bl-text.htm):

> This file contains the bulk of the spam domains. It is updated infrequently and therefore need not be downloaded more than once a week. **You must not download it more than once a day or your IP address may be blocked without notice**:
https://www.joewein.net/dl/bl/dom-bl-base.txt

**Comment by Cauchon** [comment]
I thought the same, but I haven't been able to hit it and I've tried on several different IPs.

**Comment by stordoff** [comment]
My Pi-hole isn't set to use that list, so this should be my first request, and it still gets 403d (https://www.joewein.net/dl/bl/dom-bl.txt with a looser policy also was initially blocked then allowed a few minutes later).

One of my remote servers that definitely will have NEVER requested that file also gets a 403 as a response to `curl https://www.joewein.net/dl/bl/dom-bl-base.txt`

**Comment by WaLLy3K** [comment]
Since the URL’s are [still listed here](http://joewein.net/spam/bl-text.htm), it makes me believe this is an error on their behalf.

Not sure to make of it at this point, but I *should* remove their list as they make it accessible as a part of a trial based honour system.

**Comment by Perflyst** [comment]
I can access the url and use the list. Works fine here!

**Comment by Cauchon** [comment]
Closing out.
