### ISSUE TITLE
false positive found

### ISSUE THREAD

**Issue by humsg** [WaLLy3K/wally3k.github.io#161]
Hi, I track down from oisd.nl list, link below for list is included:
https://v.firebog.net/hosts/JoeyLane.txt,
please remove d.ifengimg.com from your list, and it is image url for news site of www.ifeng.com

thank you

**Comment by hagezi** [comment]
ping @sjhgvr

**Comment by sjhgvr** [comment]
> ping @sjhgvr

Fixed. Thanks

**Comment by humsg** [comment]
thank you

**Comment by WaLLy3K** [comment]
@JoeyLane discontinued this list long ago, and I strongly discourage anyone from using it. However, it's been requested that I don't delete the latest cached copy of previously discontinued lists which is why it's visible via that link and not on the front of firebog.net 🙂
