### ISSUE TITLE
wytyphoji.pro&popup invalid domain

### ISSUE THREAD

**Issue by innug** [WaLLy3K/wally3k.github.io#165]
i found this:

[i] Analyzed 21021 domains, 1 domains invalid!
      Sample of invalid domains:
      - wytyphoji.pro&popup
MfG innug

**Comment by WaLLy3K** [comment]
I had noticed this and fixed it the day I had the new parser go live, but apparently Cloudflare desperately wanted to hang onto that file. I've tweaked the caching rules to hopefully prevent that from happening again.

Thanks :)
