### ISSUE TITLE
False Positive Found - Readme needs some love.

### ISSUE THREAD

**Issue by Tater-K7S5A** [WaLLy3K/wally3k.github.io#166]
Thank you for providing these lists.  Your hard work is appreciated.

I'm sorry for starting an issue for this but the instructions for reporting a false positive in the readme tell me to identify the maintainer but don't tell me where or how to do that.  It doesn't seem to be here, but it doesn't say where it is.

In any case: https://v.firebog.net/hosts/RPiList-Phishing.txt lists the domain 'connect.secure.wellsfargo.com' which is in fact the login page for Wells Fargo Bank.  The next entry is that string plus a string of '.auth.login.present.stonehamweb.com'.   I assume the legit domain got copy/pasted in by mistake during an update.

Thank you again.

**Comment by WaLLy3K** [comment]
Fair enough regarding how to identify the maintainer. In this case you're best to submit a ticket to https://github.com/RPiList/specials/issues

**Comment by Tater-K7S5A** [comment]
Thank you for the direction.  I have submitted the issue there.  Have a great day.
