### ISSUE TITLE
CSV File is dead 

### ISSUE THREAD

**Issue by fritterhoff** [WaLLy3K/wally3k.github.io#169]
The CSV formated Version located at https://v.firebog.net/hosts/csv.txt is unreachable

**Comment by WaLLy3K** [comment]
I'm looking at my backed up copy of this and going "where the hell was I automating the update of this?"

Unfortunately I'm not in a position where I'm able to fix this for probably the next two weeks or so, but I'll see what I can do. 🙂

**Comment by fritterhoff** [comment]
Well at least now the file is available again :)

**Comment by WaLLy3K** [comment]
Stuff it, I've done it regardless of my injured hand 😅 

I've integrated this into https://v.firebog.net/hosts/lists.php?type=csv, and a redirect can still found at the [old URL](https://v.firebog.net/hosts/csv.txt).

**Comment by WaLLy3K** [comment]
Many thanks @fritterhoff, I had honestly *completely* forgotton about this feature as it's not something I personally use.

If there's any issues with it, please let me know!
