### ISSUE TITLE
Spaces added to some adlists, Breaks the list

### ISSUE THREAD

**Issue by sml156** [WaLLy3K/wally3k.github.io#17]
On two of your text based lists located here: https://v.firebog.net/hosts/lists.php

Specifically these two
https://v.firebog.net/hosts/lists.php?type=all
and
https://v.firebog.net/hosts/lists.php?type=nocross

You have some added spaces (or maybe two tabs) at the end of four entries that start with this URL
https://gist.githubusercontent.com/CHEF-KOCH/

This breaks those lists in PiHole

By the way thanks for your hard work

**Comment by WaLLy3K** [comment]
Hey @sml156,

Thank you **very** much for letting me know! I've deployed a fix that'll be immediately available :smiley:
