### ISSUE TITLE
login.microsoftonline.com found on ticked list phishing-filter-hosts.txt

### ISSUE THREAD

**Issue by haasanen** [WaLLy3K/wally3k.github.io#170]
Related #168, #154

The entry:
```txt
0.0.0.0 login.microsoftonline.com
```
Is found on the ticked list: https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt
It is also found on its mirror: https://curbengh.github.io/malware-filter/phishing-filter-hosts.txt

It has been reported by someone else too: https://gitlab.com/malware-filter/phishing-filter/-/issues/45

This is the login page for Microsoft Outlook and Microsoft Office 365. My email stopped working when using this list.

**Comment by WaLLy3K** [comment]
I'm glad to see there's an issue open for this, because that's a *really* bad one to have blocked 🙁 
https://gitlab.com/malware-filter/phishing-filter/-/issues/45

**Comment by WaLLy3K** [comment]
https://gitlab.com/malware-filter/phishing-filter/-/issues/43

Maintainer states the list has been updated but hasn't updated the `-hosts` list that I link to.

They also state this, which is the mechanism that I believed was tick worthy:
> There is a built-in mechanism to exclude top 1m domains, somehow it doesn't work this time.
