### ISSUE TITLE
https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt  

### ISSUE THREAD

**Issue by Choppra** [WaLLy3K/wally3k.github.io#171]
This link can't be improved but you have it marked as a green check.

The cert they're using as expired likely.

**Comment by WaLLy3K** [comment]
HSTS + The certificate for hostfiles.frogeye.fr expired on 11/13/2022.

I'm looking into how I can reach out to the maintainer.

**Comment by WaLLy3K** [comment]
I pulled his website up via Google cache, and shot him through an email. All of his major contact methods run through his domain, which I suspect is the same expired cert - and I know he doesn't frequent Twitter.

I'm sure it'll get sorted out as soon as he gets a moment, regardless of whether he sees my email 🙂

**Comment by WaLLy3K** [comment]
Maintainer got back to me a couple of hours ago to let me know this has been sorted!
