### ISSUE TITLE
Whitelisting Codeberg.org

### ISSUE THREAD

**Issue by HomemadeAdvanced** [WaLLy3K/wally3k.github.io#173]
Hello, after the Mastodon post https://social.anoxinon.de/@Codeberg/109565634287806715 by Codeberg I checked my PiHole filter lists and found out that the list https://v.firebog.net/hosts/Prigent-Malware.txt now contains codeberg.org. Could you please remove this domain. Thank you very much.

**Comment by WaLLy3K** [comment]
https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi

This is where you submit a request for this particular list. Once it's been actioned, I can manually refresh the list from the source 🙂

**Comment by HomemadeAdvanced** [comment]
Allright thanks for the fast help.
