### ISSUE TITLE
3 incorrect domains: clickbicom, snortedbincom, webytom

### ISSUE THREAD

**Issue by Ad-Blokker** [WaLLy3K/wally3k.github.io#174]
Already reported the issue on the easylist github but they do not recommend easylist for pihole, so I hope that you can make a change in the parser to filter these kinds of domains:
https://github.com/easylist/easylist/issues/14740

### Domains:

```
- clickbicom
- snortedbincom
- webytom
```

### What happens?

Parsing error in pihole:

```
  [i] Target: https://v.firebog.net/hosts/Easylist.txt
  [✓] Status: No changes detected
  [i] Analyzed 20420 domains, 3 domains invalid!
      Sample of invalid domains:
      - clickbicom
      - snortedbincom
      - webytom
```

```https://v.firebog.net/hosts/Easylist.txt```

In:
`Pi-hole v5.15 ~ FTL v5.20.1 ~ Web Interface v5.18.1`

**Comment by WaLLy3K** [comment]
> @Ad-Blokker Sorry, evidently forgot to tell you that actually I had removed the filters https://github.com/easylist/easylist/commit/a9e61441602ba82944e8517469cf5de7546d84f0 shortly before closing here.

Fortunately, this will fix the issue you're seeing and my parsed copy will automatically update within three days.

**Comment by Ad-Blokker** [comment]
Ah thanks for the fast response and explanation! I didn't see the additional comment yet. Feel free to close this issue!

**Comment by Ad-Blokker** [comment]
I also didn't want to insinuate that it was a parsing error indeed. I could see that the domains were wrong in the upstream and therefore were parsed correctly. I could have made this more clear.

I also understand that you don't want to built in a domain validator as this brings complexity and possible unwanted side effects for domains that should not even be added on the upstream.

Great work!

**Comment by WaLLy3K** [comment]
Yeah, no worries at all - the bulk of that comment is more me taking a moment to explain things just so it's out there on record, especially since the whole "converting a filter list to DNS" thing isn't exactly kosher, understandably, by their standards.
