### ISSUE TITLE
URL-only text list for porn blocklists

### ISSUE THREAD

**Issue by m319** [WaLLy3K/wally3k.github.io#177]
Can you please add an URL-only text list for porn blocklists similar to your Ticked lists found here: https://v.firebog.net/hosts/lists.php
This way those who want to add the porn blocklists in an automated way similar to your other URL-only lists have that option.

It could probably be set to https://v.firebog.net/hosts/lists.php?type=porn or similar.

**Comment by m319** [comment]
@WaLLy3K

**Comment by WaLLy3K** [comment]
I currently don't see a use-case for adding this feature, as the adult blocklists [have not changed for the last two years](https://github.com/WaLLy3K/wally3k.github.io/blame/master/index.html#L121).

I have no plans of adding more and [Prigent-Adult.txt](https://v.firebog.net/hosts/Prigent-Adult.txt) is highly likely to cover _anything_ that a potential new list may contain.

Let me know your thoughts on why it's worth reconsidering 🙂

**Comment by WaLLy3K** [comment]
I'll take a look at it either this weekend or next. If it's simple enough, I'll throw it in - no promises though 🙂

**Comment by WaLLy3K** [comment]
https://v.firebog.net/hosts/lists.php?type=adult

It only looks up the words "adult" or "porn" for now. If that changes in the future, I'll update the [note here](https://v.firebog.net/hosts/lists.php)!
