### ISSUE TITLE
Barbblock Link 404

### ISSUE THREAD

**Issue by KnightmareVIIVIIXC** [WaLLy3K/wally3k.github.io#178]
@WaLLy3K This link is giving a 404 error: https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt

This one works: https://raw.githubusercontent.com/paulgb/BarbBlock/main/blocklists/hosts-file.txt

**Comment by WaLLy3K** [comment]
The `paulgb.github.io` page seems to work fine for me. GitHub pages links are preferable to `githubusercontent.com` as they contain the `last-modified` HTTP header which allows Pi-hole to view if there's any changes to a blocklist without having to download the whole thing.

**Comment by KnightmareVIIVIIXC** [comment]
Hey @WaLLy3K ! Thank you for the reply. I only use the githubuscontent link because that's the only way I know to get adguard to read the list properly. Can you give an example of another link to use?
