### ISSUE TITLE
PiHole cant get https://mirror1.malwaredomains.com/files/justdomains

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#18]
[i] Target: mirror1.malwaredomains.com (justdomains)
  [✗] Status: Internal Server Error
  [✗] List download failed: no cached list available

The strange thing i:, if i open the URL on PC, i got the file but PiHole cant get the file.

**Comment by WaLLy3K** [comment]
That's odd! `curl -so /dev/null -w "%{http_code}" https://mirror1.malwaredons.com/files/justdomains` returns `200`.

What does it return from your machine?

**Comment by beerisgood** [comment]
If i run this command i dont get any output:
`pi@raspberrypi:~ $ curl -so /dev/null -w "%{http_code}%" https://mirror1.malwaredons.com/files/justdomains
000%pi@raspberrypi:~ $
`

**Comment by WaLLy3K** [comment]
Looking back at that, of course it's going to be `000` when I've asked you to get the output for `mirror1.malwaredons.com` which clearly isn't a valid site :joy: 

Try this instead:
`curl -so /dev/null -w "%{http_code}%" https://mirror1.malwaredomains.com/files/justdomains`

**Comment by beerisgood** [comment]
No other output:

> pi@raspberrypi:~ $ curl -so /dev/null -w "%{http_code}%" https://mirror1.malwaredomains.com/files/justdomains
200%pi@raspberrypi:~ $

Also i have the same problem with the filterlist with smartphone and mobile network.

**Comment by WaLLy3K** [comment]
200 means everything is okay, and it should work fine. What list do you mean when you say filterlist?

**Comment by beerisgood** [comment]
I use the DNS66 app from F-Droid on my smartphone and the malwaredomain "filterlist" doesnt work mostly so i guess it exist a problem with the malwaredomain server

**Comment by beerisgood** [comment]
StevenBlack provide lists which use this filterlist and doesnt make problems so i close this issue as a solution is founded

**Comment by MattL0** [comment]
https://mirror1.malwaredomains.com/files/justdomains  gives 


Not Found

The requested URL /files/justdomains was not found on this server

**Comment by BananaAcid** [comment]
gives me a 404 as well

**Comment by pogletree** [comment]
https://mirror1.malwaredomains.com/files/justdomains has been euthanized by its host that moved to subscription service. They supposedly have promised a "free" version but I can't find any further info.

**Comment by tux-box** [comment]
Per "https://riskanalytics.com/community/"
As of November 30th, 2020, both AutoShun and Malware Domains feeds will be shut off, and subscribers will no longer receive intel from those sources. 

Are there any updates on how to change the underlying configs to point to a different location?

**Comment by WaLLy3K** [comment]
> Are there any updates on how to change the underlying configs to point to a different location?

What, delete the list in Pi-hole? Or do you mean something else?

**Comment by tux-box** [comment]
> > Are there any updates on how to change the underlying configs to point to a different location?
> 
> What, delete the list in Pi-hole? Or do you mean something else?

I figured out how to make the modification to remove the error, thank you for your reply.
I was wanting to know if there are any updates replacing the functionality that was provided by that list?

**Comment by WaLLy3K** [comment]
If there is, I'm not aware of any. If I know of any, I'm happy to update the list 🙂
