### ISSUE TITLE
Non-mirrored version

### ISSUE THREAD

**Issue by jacklul** [WaLLy3K/wally3k.github.io#180]
I wonder if there would be any chance you could add an optional parameter to `lists.php` that replaces `v.firebog.net` mirrored lists with their original URLs?
Pi-hole parses adblock formatted lists, someone might want to pull directly from upstream list or update way more often than your update scripts do.

Just a suggestion!

**Comment by WaLLy3K** [comment]
Suggestions are always welcome! 🙂 

I won't be able to do that without reworking the front page of [firebog.net](https://firebog.net) as `lists.php` scrapes a copy of the HTML and parses the useful output into plaintext. As the front page stands, the "maintainer sources" links back to the maintainer's site or repo to allow users to direct change requests upstream.

If I did make this change, I'd still need to filter out certain URLs such as the Fabrice Prigent lists, which are only provided as a compressed archive - but it would still benefit those eager to get the freshest copy of an adblock-style list, or the "RPiLists".

Approaching this from another angle, it's worth noting that my mirrored lists update four times a week (except for `Prigent-Adult.txt` which updates twice a week). So if you're finding that lists are updated upstream and haven't propogated to the mirrored copy, then I can definitely look into tuning how aggressively Cloudflare is caching content which *should* be for only 24 hours.

There's also [this Pi-hole (or rather, `curl`) issue](https://github.com/pi-hole/pi-hole/issues/5263) that's worth keeping note if that at all might be relevant to you!

**Comment by PromoFaux** [comment]
> I've also found another issue where Pi-hole is taking domains from filters blocking only specific elements.

Do you have a reproducable example of this? That shouldn't be happening. If so, please raise an issue here: https://github.com/pi-hole/pi-hole/issues
