### ISSUE TITLE
Spotify Connect domain blocked

### ISSUE THREAD

**Issue by panzer-arc** [WaLLy3K/wally3k.github.io#181]
dealer.spotify.com needs to be removed from [https://v.firebog.net/hosts/RPiList-Malware.txt](https://v.firebog.net/hosts/RPiList-Malware.txt)
Blocking this domain prevents Spotify Connect/Google cast functionality from working properly.
See also [https://github.com/RPiList/specials/issues/997](https://github.com/RPiList/specials/issues/997)
The maintainer of that list has closed the issue and alleged the domain has been removed already. I'm not sure why it is still blocked on the firebog.net list, so I'm opening an issue here. I'm struggling to find where the original list is in this German language repository to confirm the removal of the domain in question.

**Comment by WaLLy3K** [comment]
There was an issue that was preventing my script from running automatically. I still need to investigate and resolve that, but I've manually run the update which is effective immediately.
