### ISSUE TITLE
static/w3kbl.txt inculde space after domain

### ISSUE THREAD

**Issue by LuckyTurtleDev** [WaLLy3K/wally3k.github.io#187]
The `quantummetric.com` in https://v.firebog.net/hosts/static/w3kbl.txt has a space behind it. Which cause that I can not load this list:
```
Error: Unexpected token
    ╭─[https://v.firebog.net/hosts/static/w3kbl.txt:53:18]
    │
 53 │ quantummetric.com
    │                  ┬
    │                  ╰── Unexpected token
    │
    │ Note: Expected '\r', '.', end of file, '\n'
────╯
```

**Comment by WaLLy3K** [comment]
There were several entries with this issue, which I've now resolved. Thanks for bringing it to my attention! 🙂
