### ISSUE TITLE
CoinBlockerLists is Outdated (new url)

### ISSUE THREAD

**Issue by lychnecross** [WaLLy3K/wally3k.github.io#190]
https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser has not been updated since 2021-07-05. I believe the current list is https://zerodot1.gitlab.io/CoinBlockerLists/hosts . That one was updated on 2023-11-14 and has considerably more domains. 

The only formats updated from this repository are hosts, list.txt, and list_optional.txt. Everything else is pretty old.

**Comment by WaLLy3K** [comment]
As I understand, there are different categories in ZD1's repo and I've noticed some issues with the proposed list:

* Hosts Browser (the current rec'd list): This list contains all browser mining domains - A hostslist to prevent browser mining only
* Hosts (the proposed list): Not separately listed on [ZeroDot1's downloads page](https://zerodot1.gitlab.io/CoinBlockerListsWeb/downloads.html), but the download claims it's still browser based despite having more entries than [the list dedicated to blocking mining on networks](https://zerodot1.gitlab.io/CoinBlockerLists/list.txt).

As I don't believe the new lists purpose is *only* browser-based, it'd be unreasonable to change the purpose of the list entirely to break mining that people are (more likely) voluntarily running on their machines.

I do appreciate you opening this though - if there's a more up to date browser mining list, I'm all for updating it. 🙂

**Comment by WaLLy3K** [comment]
> It didn't occur to me that the two lists might have different purposes.

No worries at all, I figured that's what was happening. 🙂 [ZD1 said over Mastodon](https://mastodon.social/@katze/111561413762423799) that the browser list will be directly getting an update in the future, so I'm glad to hear it's not dead.

I'll mark this ticket as resolved.
