### ISSUE TITLE
Incorrect domain name

### ISSUE THREAD

**Issue by darnir** [WaLLy3K/wally3k.github.io#192]
I found an incorrect domain name: welcome..org in the easyprivacy list.
I've already filed an issue upstream about it: https://github.com/easylist/easylist/issues/18256

Mentioning it here to see if it could be explicitly stripped out.

**Comment by WaLLy3K** [comment]
I'll have to check what's going on with the validator that's allowing that. I should be able to find time a little later this week 🙂

**Comment by WaLLy3K** [comment]
Looking over my code, I don't actually perform *any* domain validation. For some reason, I thought I did. However, I've taken the time to clarify my stance in the [readme](https://github.com/WaLLy3K/wally3k.github.io?tab=readme-ov-file#on-the-subject-of-non-domain-entries) *(in that basically, I don't feel I should be making these kinds of changes and that Pi-hole does it already)*.

If you're not using Pi-hole and this issue still affects you, let me know 🙂
