### ISSUE TITLE
False Positive in Firebog list

### ISSUE THREAD

**Issue by 4L3xN3t** [WaLLy3K/wally3k.github.io#193]
Hi,
don't know if this is the right place to report this issue, but I have no account in any of the services found at the page https://firebog.net/about to report false positive to the developer.
I found today that the url api-app.io.pagopa.it is in the https://v.firebog.net/hosts/RPiList-Malware.txt list but that address is an Italian governative web service to manage payment of various public services or taxes used for example by the governative app "IO" (https://play.google.com/store/apps/details?id=it.pagopa.io.app&hl=it&gl=US)
It definitely souldn't be blocked!

**Comment by WaLLy3K** [comment]
Doesn't sound like it should be!

The best place to report that is here: https://github.com/RPiList/specials

While it is German, they will happily converse in English. I'd also just shoot off an issue myself, but I won't have time till a little later this week 🙂

**Comment by 4L3xN3t** [comment]
thank you, just reported 
have a nice day ;)

**Comment by WaLLy3K** [comment]
[Actioned](https://github.com/RPiList/specials/issues/1475#issuecomment-1953279938)
