### ISSUE TITLE
Two non-domain entries in Easylist

### ISSUE THREAD

**Issue by JoniRousu** [WaLLy3K/wally3k.github.io#194]
Pi-hole reports two non-domain entries when updating gravity (Easylist): 

- "iqkufk"
- "spryptvqguhpwt"

**Comment by WaLLy3K** [comment]
Thanks - I'll need to check to see why the validator is allowing entries like that to remain.

**Comment by WaLLy3K** [comment]
Looking over my code, I don't actually perform *any* domain validation. For some reason, I thought I did. However, I've taken the time to clarify my stance in the [readme](https://github.com/WaLLy3K/wally3k.github.io?tab=readme-ov-file#on-the-subject-of-non-domain-entries) *(in that basically, I don't feel I should be making these kinds of changes and that Pi-hole does it already)*.

**Comment by JoniRousu** [comment]
Alright, thanks for looking into it!
