### ISSUE TITLE
investigate / remove disconnect.me

### ISSUE THREAD

**Issue by jniggemann** [WaLLy3K/wally3k.github.io#195]
I just came across this 2y old thread on [reddit](https://www.reddit.com/r/pihole/comments/wtizpa/deprecation_of_disconnectme_adlists_recommended/) where it says:

> I noticed that the highly recommended adlist resource https://firebog.net/ has at least 2 adlists that are deprecated, but continue to be color-coded green.

>We contacted Disconnect.me ([support@disconnect.me](mailto:support@disconnect.me)) and they shared this with us:
>>The list you referenced was used in our legacy products. It is not maintained, has not been updated, and is not actively distributed us.

I'm not sure about the validity of a random reddit post, but perhaps it _is_ valid and no one bothered to make you aware?

**Comment by WaLLy3K** [comment]
I'm only made aware when people let me know. I'll definitely remove them if they're not supported, since one of the point of tick lists is that they're being regularly updated. 🙂

I'll find some time to do that this week, thanks!

**Comment by WaLLy3K** [comment]
I appreciate you bringing this up, because it's not like the maintainers or anyone else lets me know. I suppose I should look into having some kind of stale alert, where it pings me if it hasn't been updated in six months.

Thanks 🙂

**Comment by jniggemann** [comment]
> I appreciate you bringing this up, because it's not like the maintainers or anyone else lets me know.
:-)

> I suppose I should look into having some kind of stale alert, where it pings me if it hasn't been updated in six months.
```
jn@notebook:~# curl -s -v -X HEAD https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt 2>&1 | grep '^< Last-Modified:'
< Last-Modified: Sat, 01 Feb 2020 02:37:09 GMT
```

**Comment by WaLLy3K** [comment]
Yeah, I already parse that information from `curl` so it'd be nothing for me to hook into my Pushover account. I just need to find time *and* motivation to code 🙂
