### ISSUE TITLE
CHEF-KOCH lists

### ISSUE THREAD

**Issue by eejeel** [WaLLy3K/wally3k.github.io#2]
Why not add the original lists from https://github.com/CHEF-KOCH/NSABlocklist/tree/master/Trackers for the CHEF-KOCH Anti-Fingerprinting lists? It has standard short URL's

This is your list and the original URL's. I also add the NSABlocking list of his site

# CHEF-KOCH Anti-Fingerprinting lists
# https://github.com/CHEF-KOCH/NSABlocklist/tree/master/Trackers
https://gist.githubusercontent.com/CHEF-KOCH/080efada22b9659ef61241029122873b/raw/7f9bd984d3c46b3dba2de7606da579bc0ac6780c/Canvas%2520Font%2520Fingerprinting%2520pages%2520%255B2017%2520Edition%255D
https://github.com/CHEF-KOCH/NSABlocklist/raw/master/Trackers/Canvas%20font%20fingerprinting.txt

https://gist.githubusercontent.com/CHEF-KOCH/5a7b1593d1880f906b12a3c87cee4500/raw/3ba028508feb2ef67a3d7ab75f428fd284223e8b/WebRTC%2520tracking%2520list%2520%255B2017%2520Edition%255D.txt
https://github.com/CHEF-KOCH/NSABlocklist/blob/master/Trackers/webrtc%20tracking.txt

https://gist.githubusercontent.com/CHEF-KOCH/63fd2e506cb34a2378ad2620ab06d2e0/raw/fb9f16e3ac998d3f773ebdfee4aa3bfd10a5d763/Audio%2520fingerprint%2520pages%2520%255B2017%2520Edition.exe
https://github.com/CHEF-KOCH/NSABlocklist/raw/master/Trackers/audio%20fingerporint%20pages.txt

https://gist.githubusercontent.com/CHEF-KOCH/2dea75d43b2184f228ae94b168d275b1/raw/35d7a4447a198449bbb3280e1c3d7a57517350de/Canvas%2520fingerprinting%2520pages%2520%255B2017%2520Edition%255D.exe
https://github.com/CHEF-KOCH/NSABlocklist/raw/master/Trackers/canvas%20fingerprinting%20pages.txt

https://github.com/CHEF-KOCH/NSABlocklist/raw/master/Trackers/trackers.txt

#  NSABlocklist/HOSTS
# https://github.com/CHEF-KOCH/NSABlocklist
https://raw.githubusercontent.com/CHEF-KOCH/NSABlocklist/master/HOSTS

**Comment by WaLLy3K** [comment]
I added CHEF-KOCH's Fingerprinting/Trackers because they're useful and from what I've gleaned/tested, don't appear to have any false positives. If I find that it does, I'll contact the maintainer regarding it, and if necessary, de-tick the lists.

The NSA Blocklist contains what appear to be legitimate government websites, which is why I've hesitated putting that list up. While this thought doesn't factor into my decision, I reckon that if you're being targeted by the NSA, an outdated blocklist like this isn't going to help you. :smile:

**Comment by Atavic** [comment]
Unless you backed it up, anything from CHEF-KOCH is gone.

**Comment by WaLLy3K** [comment]
For some reason, I wasn't using his lists on my own install - so I've got no backup :frowning_face: 

I'll make the changes to the big blocklist now, so thank you for letting me know.

**Comment by beerisgood** [comment]
I ask CHEF-Koch whats going on and got that:

> flagged my account via their indexing bots, so my account is not visible until this is resolved.

**Comment by Atavic** [comment]
:+1: It's all back for good.

**Comment by WaLLy3K** [comment]
I've [added these lists again](https://github.com/WaLLy3K/wally3k.github.io/commit/53233684612754322c1f64f29d8773b5ce37528f).
