### ISSUE TITLE
Android Tracking blocklist

### ISSUE THREAD

**Issue by Perflyst** [WaLLy3K/wally3k.github.io#20]
I collected some domains which are used by some android apps for collection user data.

They are not in the adaway lists, because these are only for adblocking, not for telemetry and tracking.

The list will be constantly expanded. Would be nice if you add it on your collection.
https://github.com/Perflyst/PiHoleBlocklist/blob/master/android-tracking.txt

**Comment by Perflyst** [comment]
It gets also called from other non-facebook apps and services. I deny facebook completely.
Whatsapp calls it, but there is no need. There is also `graph.instagram.com` which is only for tracking stuff needed.
But if necessary I will whitelist it.

Which functions will be blocked?

**Comment by WaLLy3K** [comment]
> Which functions will be blocked?

Honestly, I can't remember and since no one in my household uses Facebook any more, it's not something I can test. As a result: I'm happy to add the list, but it just won't be checkmarked!
