### ISSUE TITLE
Blocklist Suggestions

### ISSUE THREAD

**Issue by KnightmareVIIVIIXC** [WaLLy3K/wally3k.github.io#203]
Author:
@erkexzcx

About:
Disconnectme JSON files converted to Pi-Hole compatible blocklists

Homepage:
https://github.com/erkexzcx/disconnectme-pihole

Lists to add:
https://raw.githubusercontent.com/erkexzcx/disconnectme-pihole/master/services_FingerprintingInvasive.txt
https://raw.githubusercontent.com/erkexzcx/disconnectme-pihole/master/services_Anti-fraud.txt
https://raw.githubusercontent.com/erkexzcx/disconnectme-pihole/master/services_Cryptomining.txt
https://raw.githubusercontent.com/erkexzcx/disconnectme-pihole/master/services_Social.txt
https://raw.githubusercontent.com/erkexzcx/disconnectme-pihole/master/services_Analytics.txt
https://raw.githubusercontent.com/erkexzcx/disconnectme-pihole/master/services_FingerprintingGeneral.txt
https://raw.githubusercontent.com/erkexzcx/disconnectme-pihole/master/services_Advertising.txt

**Comment by erkexzcx** [comment]
Maintainer of that repo here. I stopped using these blocklists due to large amount of false positives. I don't recommend to use them.
