### ISSUE TITLE
Dead source

### ISSUE THREAD

**Issue by Yesfinethankyou** [WaLLy3K/wally3k.github.io#22]
the below source 404s

https://raw.githubusercontent.com/StevenBlack/hosts/master/data/tyzbit/hosts

**Comment by beerisgood** [comment]
Can confirm that

**Comment by s1awa** [comment]
WaLLy3K already changed it to
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win10/spy.txt
that was Steven Black's source

**Comment by WaLLy3K** [comment]
Ah yes, this was brought to my attention via Reddit! Notifications on GH are a PITA, so I don't get the opportunity to action open issues as quickly as I like.

Thank you @Yesfinethankyou and @s1awa

**Comment by beerisgood** [comment]
@WaLLy3K with the Android APP Fasthub-Libre from F-Droid GH notifications much better then on desktop

**Comment by WaLLy3K** [comment]
I appreciate the tip, despite being an iOS user! I actually went for a paid upgrade to [CodeHub](http://codehub-app.com) which now lets me get updates on my phone and watch. :smile:

**Comment by crazy-max** [comment]
@WaLLy3K I have merged rules in the latest release of [WindowsSpyBlocker](https://github.com/crazy-max/WindowsSpyBlocker) fyi :

https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win10/spy.txt

becomes

https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
