### ISSUE TITLE
ad.doubleclick.net

### ISSUE THREAD

**Issue by kodxana** [WaLLy3K/wally3k.github.io#24]
It is possible to block this type of adds?

**Comment by WaLLy3K** [comment]
Definitely! If you're seeing ads from this domain, I'd suggest looking into [disabling QUIC in Chrome](https://discourse.pi-hole.net/t/why-do-i-see-ads-in-chome-but-not-other-browsers/3284) which is able to bypass HOSTS style adblocking.

If you find you're still having issues with ads from this domain, hit up this ticket again and I'll be happy to look into it further! :+1:
