### ISSUE TITLE
webtrack.dhlglobalmail.com blocked

### ISSUE THREAD

**Issue by arghblech** [WaLLy3K/wally3k.github.io#25]
The DHL package tracking page is blocked in list.19.v.firebog.net.domains.  I've whitelisted it and I didn't notice anything objectionable on the page.

**Comment by WaLLy3K** [comment]
If I use `pihole -q -adlist webtrack.dhlglobalmail.com`, it says that a match is found in `https://v.firebog.net/hosts/Airelle-trc.txt`. You can contact Airelle at `contact.wiki.airelle [at] spamgourmet.com` and let him know of the (potential) false positive.
