### ISSUE TITLE
reddestdream.github.io blocks Apples OCSP responder

### ISSUE THREAD

**Issue by madsky** [WaLLy3K/wally3k.github.io#28]
ocsp.apple.com is blocked by this list: https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts

Since this is a crypto service it might be worth flagging as a site worth whitelisting.  The owner of reddestdream has no obvious method of contacting them, but since the purpose of their list appears to relate to jailbreaking iPhones I'm not sure it's an accidental entry or they'd be interested in removing it.

**Comment by WaLLy3K** [comment]
If I recall from my JBing days, blocking `ocsp.apple.com` was required because otherwise it'd break a particular jailbreak due to the revocation of required certificates. I've gone ahead and opened a ticket on their repo so it can be reviewed, but you may want to contact them at `reddestdream [at] gmail.com` due to inactivity on their GitHub account.

I can add a whitelist note on my page, if that would also be suitable?

**Comment by madsky** [comment]
Hey Buddy - yeah, I don't want to create work for you, just thought that
blocking part of the Apple crypto service is probably undesirable for
most people consuming your blocklists.  Updating the page to mention it
would be awesome of you and way more than enough.
Cheers,
Leigh

--
  Leigh Hall
  leigh@madsky.co.uk



On Sun, 3 Jun 2018, at 2:27 PM, WaLLy3K wrote:
> If I recall from my JBing days, blocking ocsp.apple.com was required
> because otherwise it'd break a particular jailbreak due to the
> revocation of required certificates. I've gone ahead and opened a
> ticket on their repo so it can be reviewed, but you may want to
> contact them at reddestdream [at] gmail.com due to inactivity on their
> GitHub account.> I can add a whitelist note on my page, if that would also be suitable?> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/WaLLy3K/wally3k.github.io/issues/28#issuecomment-394162377

**Comment by WaLLy3K** [comment]
Thanks for bringing it up @madsky, I always appreciate constructive feedback :smile:
