### ISSUE TITLE
Pihole cannot update lists from v.firebog.net (Status: Forbidden)

### ISSUE THREAD

**Issue by l3d00m** [WaLLy3K/wally3k.github.io#3]
Hello,

I'm using your great adlist collection for my pihole. I have no trouble fetching those hosts with the exception of your domain, `v.firebog.net`. If I'm updating my lists using the pihole web interface, it looks like this (excerpt):

```
::: Getting s3.amazonaws.com list... done
:::   Status: Not modified
:::   No changes detected, transport skipped!
::: Getting v.firebog.net list... done
:::   Status: Forbidden
:::   Download failed and no cached list available (list will not be considered)
  [TRUNCATED as I have multiple lists of this host, they all fail]
::: Getting v.firebog.net list... done
:::   Status: Forbidden
:::   Download failed and no cached list available (list will not be considered)
::: Getting www.dshield.org list... done
:::   Status: Success (OK)
:::   List updated, transport successful!
```

My `adlists.list` is the same as [your nocross adlist collection](https://v.firebog.net/hosts/lists.php?type=nocross)

**I have no problem to `wget` one of the urls, for which pihole returns `Forbidden`. This happened on the same machine.**

Is this maybe some kind of misconfiguration of your hoster that it doesn't allow pihole? Or am I the only one with that problem?

**Comment by WaLLy3K** [comment]
I've just ran `pihole -g -f` to force update my lists on both my RPi3B running the latest development version, as well as on my secondary RPi Zero running Master. All my `v.firebog.net` sourced lists work as expected.

I use Cloudflare to mirror my lists, and have intentionally changed the [security level to "Essentially Off"](https://support.cloudflare.com/hc/en-us/articles/200170056-What-does-Cloudflare-s-Security-Level-mean-) (the lowest security setting the free plan offers) which supposedly "challenges only the most grievous offenders".

Unless you're using a VPN or Tor, I have absolutely no idea why CF would be forbidding your requests. May I suggest you try getting a new WAN IP and trying again?

**Comment by l3d00m** [comment]
Hey @WaLLy3K, thanks for the quick response!

I figured where the problem is by now and why you don't expierence it. It is fixed with [this commit in pi-hole](https://github.com/pi-hole/pi-hole/commit/6a2b885988673ce60de78af85fcb69d284a836c4). The browser header wasn't accepted by cloudflare. You should note that your list *probably* isn't working for anyone who uses the newest pihole version and not pihole-dev.

*Here's a small writeup I did, this is mostly irrelevant now knowing it was already fixed in pihole.*

As my issue was quite unsepcific, I dug a little bit into the pihole code. I found that pi-hole is using `curl` instead of `wget`. This happens [here](https://github.com/pi-hole/pi-hole/blob/b0eceddcec2054273d7e1add34d1f806b0c81693/gravity.sh#L151). 

I echoed the command used, which for me is:

`curl -s -L   -w %{http_code} -A "Mozilla/10.0" https://v.firebog.net/hosts/Prigent-Malware.txt -o /tmp/tmp.b0TtVy12ZB`

Relevant bits of the result:

```
The owner of this website (v.firebog.net) has banned your access based on your browser's signature (392502426e9e2726-ua31).
```

Which means the header specified with the `-A` was at fault. As soon as I used a newer header, I no longer get a 403 and was able to get the list.

The agent is definied [here](https://github.com/pi-hole/pi-hole/blob/b0eceddcec2054273d7e1add34d1f806b0c81693/gravity.sh#L214)

**Comment by WaLLy3K** [comment]
Ah yes! The old header was definitely the cause of a lot of issues, and you're right, an un-updated install could definitely cause that! :smile:

**Comment by l3d00m** [comment]
Yep, everything works now for me after a reinstall. Sorry for the troubles and thank you for that collection and rehosting!
