### ISSUE TITLE
Airelle-trc blocks "medium.com"

### ISSUE THREAD

**Issue by bobsoppe** [WaLLy3K/wally3k.github.io#30]
`medium.com` looks like a false-positive to me. Not really a website that distributes malware, is a host for ads, etc.

Airelle-trc looks like to host multiple false-positives #27 and #29.

**Comment by Dustee** [comment]
I just noticed today that the European Commission website is also on this list. [ec.europa.eu]
I'm personally removing Airelle-trc from my setup for now, too many false positives...

**Comment by WaLLy3K** [comment]
Hi @bobsoppe and @Dustee 

Sorry for the inconvenience! I've contacted the list maintainer regarding these false positives, and I've taken action by removing Airelle lists from the tick recommendation.

**Comment by tripad** [comment]
As of today "medium.freecodecamp.org" is also a false negative on the same domain
