### ISSUE TITLE
Airelle-trc blocks aws.amazon.com

### ISSUE THREAD

**Issue by lightswitch05** [WaLLy3K/wally3k.github.io#31]
Amazon's AWS service is used for general computing. While it could be for tracking, it is also the core of many legitimate services and applications. Blocking this breaks things for me, and I suspect I'm not the only one. It looks like there are several other tickets against this list for false positives. If you do not believe these to be false positives, then I would recommend updating the website to have a cross in front of this list:

> Lists bulleted with a cross block multiple useful sites (e.g: Pi-hole updates, Amazon, Netflix)

The description is especially relevant since the service being blocked is actually Amazon

**Comment by WaLLy3K** [comment]
I agree, it's completely inappropriate that anything blocks AWS entirely - like it or not, it's a core part of the web!

I've sent the list maintainer an email regarding this issue, and I've removed Airelle lists from my tick recommendation.

Thank you for taking the time to let me know! :smile:
