### ISSUE TITLE
text-only version of ticked list does not match the Jun 3, 2018 changes

### ISSUE THREAD

**Issue by dietavor** [WaLLy3K/wally3k.github.io#32]
The text-only version of your [ticked list](https://v.firebog.net/hosts/lists.php?type=tick) is not up to date. The two Airelle lists are still included and the WindowsSpyBlocker list still points to the old domain.

Btw will Airelle be in the ticked section again after being fixed by the maintainer?

**Comment by WaLLy3K** [comment]
> The text-only version of your ticked list is not up to date.

`list.php` is a script that caches the source of the Blocklist Collection, and refreshes it every 24 hours - so you'll find that it's up to date now! :)

> Btw will Airelle be in the ticked section again after being fixed by the maintainer?

I've been on the fence about Airelle's lists for almost a year now. While those lists are extremely useful IMHO, I've had to contact that particular maintainer more than any other regarding domains that really have no place being in a blocklist. After numerous complaints by *other* people raised here, I can't honestly say that it qualifies as being "no notable false positives" even after obvious domains have been removed from the list.
