### ISSUE TITLE
It's June, not May

### ISSUE THREAD

**Issue by XelNika** [WaLLy3K/wally3k.github.io#35]
Haha, I think it's time for you to step into the future.

https://github.com/WaLLy3K/wally3k.github.io/commit/50f7f4da2fa1201a9cc7b70783c96b8af6667640#diff-eacf331f0ffc35d4b482f1d15a887d3b
https://github.com/WaLLy3K/wally3k.github.io/commit/0e7de9ad425a5411fe28ad234226d51d0e362f53#diff-eacf331f0ffc35d4b482f1d15a887d3b

**Comment by WaLLy3K** [comment]
Whoops! 😳

Thanks for pointing it out, a silly oversight on my behalf.
