### ISSUE TITLE
Cant connect to https://wally3k.github.io

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#36]
Because i block direct IP access in my router and if i open https://wally3k.github.io
Doesnt have your site a DNS entry? https://firebog.net works fine

**Comment by WaLLy3K** [comment]
As of a change I made yesterday, https://wally3k.github.io should be automatically redirecting to https://firebog.net, which is the domain where The Big Blocklist is located. I've tested this on multiple devices, and multiple IP addresses - so I'm not sure why you're having issues with the change!

**Comment by beerisgood** [comment]
Works fine now.

**Comment by WaLLy3K** [comment]
That's a relief, thank you very much for the confirmation! :+1:
