### ISSUE TITLE
False positiv: i-technet.sec.s-msft.com

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#37]
You list i-technet.sec.s-msft.com # Technet under # Ads in your filterlist https://v.firebog.net/hosts/static/w3kbl.txt but this domain is needed for Technet sites.
See https://technet.microsoft.com/de-de/

If you block this domain, the whole site design is broken

**Comment by WaLLy3K** [comment]
While I haven't personally experienced Technet breaking due to this change, I've removed it for you - thanks for the heads up! :)
