### ISSUE TITLE
Bad list in the 'ticked lists' group

### ISSUE THREAD

**Issue by dmginc** [WaLLy3K/wally3k.github.io#39]
This list: https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Spotify-HOSTS-FilterList.txt

is breaking Spotfiy completely (in the browser at least), unless these 2 domains are whitelisted:

audio-akp-spotify-com.akamaized.net
audio-fa.scdn.co

**Comment by WaLLy3K** [comment]
That's a good heads up, since I've noticed [you've already opened a ticket with @CHEF-KOCH](https://github.com/CHEF-KOCH/CKs-FilterList/issues/24).

I'll keep this issue open until further notice.

**Comment by WaLLy3K** [comment]
Frustratingly, this is marked as `wontfix` without any further explanation why.
