### ISSUE TITLE
airelle-trc blocks cs9.wac.phicdn.net (ocsp.digicert.com)

### ISSUE THREAD

**Issue by dietavor** [WaLLy3K/wally3k.github.io#40]
The list "airelle-trc" blocks cs9.wac.phicdn.net (ocsp.digicert.com seems to be an alias) which breaks sites like github. I was wondering why the Query Log showed ocsp.digicert.com as blocked query even though I couldn´t find the domain on any of the Block Lists I use. The reason seems to be cs9.wac.phicdn.net blocked by airelle-trc.

Don´t know if this is a real issue since the airelle lists are not recommended as ticked any more. Just to let you know.

**Comment by WaLLy3K** [comment]
Hey @dietavor, I'd strongly recommend shooting Airelle an email about the issue: `contact.airelle [at] spamgourmet.com`. As you've noticed, it's not ticked any more - but I am considering marking them with a cross!

Cheers
