### ISSUE TITLE
YoYo Failure/Tie-up

### ISSUE THREAD

**Issue by tpaluch** [WaLLy3K/wally3k.github.io#41]
From the "ticked lists" // https://v.firebog.net/hosts/lists.php

Pi cannot connect to this list, and it unnecessarily ties up the update queue:
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts;showintro=0

Log:
[i] Target: pgl.yoyo.org (serverlist.php?hostformat=hosts;showintro=0)
[✗] Status: Connection Refused
[✗] List download failed: no cached list available

**Comment by WaLLy3K** [comment]
Out of interest @tpaluch, was this some temporary downtime at `pgl.yoyo.org`, or something else you encountered?

**Comment by tpaluch** [comment]
@WaLLy3K It appears to have been a temporary downtime. I checked a day later and it was back online.

**Comment by WaLLy3K** [comment]
Thanks, much appreciated!
