### ISSUE TITLE
osint.bambenekconsulting.com blocked in https://v.firebog.net/hosts/Airelle-hrsk.txt

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#45]
On https://threatfeeds.io i was try to download "C&C Domains" from "Bambenek Consulting" but the domain is blacklisted in https://v.firebog.net/hosts/Airelle-hrsk.txt
Why?

All scan results looks fine:
# https://www.virustotal.com/#/url/d8c89b40c9377caa39b8c3b35c4454703a840723cb03f56dc8d41bd59df82ce1/detection
# https://www.virustotal.com/#/domain/osint.bambenekconsulting.com
# https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fosint.bambenekconsulting.com%2F
# https://www.ssllabs.com/ssltest/analyze.html?d=osint.bambenekconsulting.com

**Comment by WaLLy3K** [comment]
Hey @beerisgood!

If you're using my tick lists, I'd recommend [updating your lists](https://v.firebog.net/hosts/lists.php?type=tick) as I've had Airelle unticked for a while now.

If you'd like to keep using the non-ticked lists (which is totally fine!) and just have this site reviewed, then I'd suggest getting in touch with Airelle at `contact.airelle [at] spamgourmet.com` who maintains that list :smile: 

Hope that helps - but if not, please reply here and let me know!

**Comment by beerisgood** [comment]
Airelle fix it btw

But the file is useless for PiHole. Damn :D
