### ISSUE TITLE
kcsoftwares.com false positiv in https://v.firebog.net/hosts/Airelle-hrsk.txt

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#48]
In your https://v.firebog.net/hosts/Airelle-hrsk.txt the site kcsoftwares.com is blocked, which is a legit software site. See https://www.virustotal.com/#/domain/kcsoftwares.com

**Comment by WaLLy3K** [comment]
Hey @beerisgood,

You'll need to send an email to `contact.wiki.airelle[at]spamgourmet.com`, as my list is auto-updated when he updates his source files.

Cheers :smile:

**Comment by beerisgood** [comment]
On 8th october the dev told me the domain looks okay.
I wonder why its still in your list then. Is it up2date with the origin?

**Comment by WaLLy3K** [comment]
Sometimes it takes time for Airelle to update his content, but I can confirm that [the original archive](http://rlwpx.free.fr/WPFF/hrsk.7z) has `127.0.0.1 kcsoftwares.com` on line 34578 (which means that my mirror is still up-to-date).

**Comment by beerisgood** [comment]
Sad. Then he doesn't care

**Comment by Atavic** [comment]
Some installs have an adware bundled, called Relevant Knowledge.

**Comment by Atavic** [comment]
ESET Internet Security was flagging the install file sumo.exe as a potentially dangerous URL in 2017.
