### ISSUE TITLE
https://ransomwaretracker.abuse.ch is dead (atm)

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#52]
After i try to open the lists under https://ransomwaretracker.abuse.ch/blocklist/ they can't be reached and i always got Error 503 Connection refused.
Then i write the guys a email and they told me:

> yes, ransomware tracker is down atm.

I already ask if they know when this will be fixed, but:

> no eta, sorry

**Comment by WaLLy3K** [comment]
I won't take down the list because downtime is just a fact of life, and Pi-hole is generally happy to use an outdated list.

Anyone can use these links though, if you prefer:
https://v.firebog.net/hosts/ZeusTrack.txt
https://v.firebog.net/hosts/RansomTrack.txt

**Comment by beerisgood** [comment]
Thanks

**Comment by beerisgood** [comment]
I see their lists are now online again
