### ISSUE TITLE
Provide Disconnect.me lists over v.firebog.net

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#53]
Can you please provide both disconnect.me lists

- https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
- https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt

over your v.firebog.net domain?
"s3.amazonaws.com" got blocked from other lists and i don't want allow too much AWS stuff

**Comment by WaLLy3K** [comment]
Anything that blocks `s3.amazonaws.com` is pretty sloppy, frankly!

These are already updated weekly, so feel free to use them:
https://v.firebog.net/hosts/Disconnect-trc.txt
https://v.firebog.net/hosts/Disconnect-mal.txt
https://v.firebog.net/hosts/Disconnect-ads.txt
