### ISSUE TITLE
facebook blocklist remove from list generator

### ISSUE THREAD

**Issue by ail1020** [WaLLy3K/wally3k.github.io#55]
Can you remove https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt from the list generator, similar to how you handled the 1 million porn list? I have a script that automatically pulls in the no-cross plaintext list and adds any missing to my adlist. I've gotten a lot of false positives since my cohabitants use facebook. It would also work to mark it as a cross.

I'm referring to this process: https://v.firebog.net/hosts/lists.php

**Comment by WaLLy3K** [comment]
Ah yeah, that's a very fair point. Done! :)
