### ISSUE TITLE
Add https://v.firebog.net/hosts/Airelle-trc.txt a cross

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#57]
[Airelle-trc.txt](https://v.firebog.net/hosts/Airelle-trc.txt) block important stuff like cdnjs.cloudflare.com
I have no motivation to write the guy again a message, cause he doesn't care: https://github.com/WaLLy3K/wally3k.github.io/issues/48

Because of that you should add at least the Airelle-trc.txt a cross. Maybe both Airelle lists

**Comment by WaLLy3K** [comment]
I have had to contact Airelle *many times* over numerous issues, and the maintainer has been happy to reply. However, I can't always be the one contacting this maintainer to ask them to resolve issues. There's been a few cases of "Why/how was that even added to your list?", but seeing `cdnjs.cloudflare.com` is just absurd.

Thanks for reporting the issue, and I appreciate your ongoing input with the repo :)
