### ISSUE TITLE
More possible sources

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#59]
WaLLy3K take a look at https://github.com/notracking/hosts-blocklists/issues/140

Maybe you find some nice lists

**Comment by beerisgood** [comment]
@WaLLy3K

**Comment by beerisgood** [comment]
*push*

**Comment by beerisgood** [comment]
*push*

**Comment by WaLLy3K** [comment]
This was opened on Feburary 25th? Yikes, that's shameful of me.

* https://tspprs.com, now https://blocklist.site - A curated blocklist that pulls from several well known sources without credit, sorted into categories, and monetised. As far as I can tell anyway.

* https://dbl.oisd.nl - Another curated blocklist, but very respectively [credits its sources](https://includes.oisd.nl/). I actually wouldn't mind going through this and adding the individual sources, but I feel that would undermine @sjhgvr's excellent work. I would consider going against my standpoint of only adding original sources if @sjhgvr has separate lists for Advertising, Tracking and Malware that I could add and therefore tick under individual categories.

* https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts and https://hosts.nfz.moe/basic/hosts - Appears to be domains targeted to the Asian market, but this isn't a *bad* thing by any means. 

* https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt - looks good, and doesn't aim to duplicate existing peoples efforts.

**Comment by nefty1029** [comment]
Hello Wally3k, is it possible to look into the list below? Maybe you can add it to your website:
https://raw.githubusercontent.com/Kees1958/WS3_annual_most_used_survey_blocklist/master/w3tech_hostfile.txt
https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-hosts.txt
https://ssl.bblck.me/blacklists/hosts-file.txt
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt

**Comment by WaLLy3K** [comment]
> Hello Wally3k, is it possible to look into the list below? Maybe you can add it to your website:
> https://raw.githubusercontent.com/Kees1958/WS3_annual_most_used_survey_blocklist/master/w3tech_hostfile.txt
> https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-hosts.txt
> https://ssl.bblck.me/blacklists/hosts-file.txt
> https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt

Wonderful, thank you for the suggestions! 🙌
