### ISSUE TITLE
Link does not work. 

### ISSUE THREAD

**Issue by dark2727** [WaLLy3K/wally3k.github.io#6]
Hi, 
Could you help me with your site. 
https://v.firebog.net/hosts/lists.php

Links on this site does not forward to the list, 
Please check it. 

Regards.

**Comment by WaLLy3K** [comment]
Hi @dark2727, this link provides a simple URL list of all the blocklists to paste into your block list config.

For example, you'd [copy everything from here](https://v.firebog.net/hosts/lists.php?type=tick) and paste them into [Pi-hole's Block Lists](http://pi.hole/admin/settings.php) on the right.

Hope this helps!

**Comment by dark2727** [comment]
Thanks a lot. 
Have a nice day.
