### ISSUE TITLE
Discord being blocked

### ISSUE THREAD

**Issue by Area45** [WaLLy3K/wally3k.github.io#60]
Don't know if this is the proper place to put this but the blocklist https://www.squidblacklist.org/downloads/dg-malicious.acl is now blocking media.discordapp.com

This causes any image from discord to not load. Should probably be added to whitelists list since this is in the default least likely to interfere with browsing group.

**Comment by beerisgood** [comment]
Are you sure?
I cannot find "media.discordapp.com" in "https://www.squidblacklist.org/downloads/dg-malicious.acl"

**Comment by Area45** [comment]
It appears it was removed since it wasn't malware. Sorry for the small panic I was a little worried people wouldn't know why their discord was being blocked.

**Comment by beerisgood** [comment]
No problem!
Please close this issue then
