### ISSUE TITLE
youtu.be being blocked

### ISSUE THREAD

**Issue by p1r473** [WaLLy3K/wally3k.github.io#61]
youtu.be is legit mirror for youtube.com 
Its in https://v.firebog.net/hosts/Airelle-trc.txt

**Comment by frankrpi3** [comment]
> Lists bulleted with a cross block multiple useful sites (e.g: Pi-hole updates, Amazon, Netflix)

If you are using those kind of blocklists, you have to whitelist more.
Otherwise you should only use the ticked lists on https://firebog.net
