### ISSUE TITLE
Problem with https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt Dev

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#63]
I already contact the Dev from "https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt" list because of a false positive but he even don't answer on official issue @Gitlab.
1 week is now passed and for me that's far too long for not any comment or change

So better mark his list not with the "tick"

**Comment by beerisgood** [comment]
*push*

**Comment by WaLLy3K** [comment]
Hi @beerisgood, are there still false positives to note of in this list? I would be happy to untick this, if there's still issues. As it currently stands though, `dmd.metaservices.microsoft.com` isn't on the list as per your ticket on his repo.

**Comment by beerisgood** [comment]
I still use his list and works fine so far so i close this issue now.
