### ISSUE TITLE
Problem with "anudeepND" Dev

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#64]
This dev looks inactive too: https://github.com/anudeepND/blacklist/issues

Also his [adservers.txt](https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt) block Windows Update servers!:
fe2.update.microsoft.com.akadns.net
ls.update.microsoft.com.akadns.net
statsfe2.update.microsoft.com.akadns.net

> Microsoft uses global load balancers that can appear in network trace-routes. For example, an endpoint for *.akadns.net might be used to load balance requests to an Azure datacenter, which can change over time.
https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-1809-non-enterprise-editions

So even a cross is required here

**Comment by beerisgood** [comment]
Another problem: https://github.com/anudeepND/blacklist/issues/46
(location.services.mozilla.com)

After 14 days still no answer.
I remove this list from my PiHole.

**Comment by anudeepND** [comment]
@beerisgood Sorry for the delay, it's been fixed now. You can close this issue

**Comment by anudeepND** [comment]
@WaLLy3K This issue resolved, you can close it

**Comment by WaLLy3K** [comment]
Thanks @beerisgood. I know I *definitely* take longer to reply to messages than @anudeepND, but thank you both for your input! 😊

If a developer is indeed inactive and is likely to cause false positives for a large amount of users (Windows Updates and Firefox definitely fits this description), then I'm happy to remove it in the future.
