### ISSUE TITLE
Airelle-trc blocks "logbuch-netzpolitik.de"

### ISSUE THREAD

**Issue by timpritlove** [WaLLy3K/wally3k.github.io#66]
Not sure what the source for "airelle-trc" is but it seems to be imported in various blocklists.

In this list, https://logbuch-netzpolitik.de/ is included which is not a tracking host but the home  page of a German podcast on net politics. Just have a look, it's just a podcast.

**Comment by WaLLy3K** [comment]
Both of Airelle's lists are listed as a cross, due to being unreliable and questionable with the results it provides. I think I recall discussing this with you on Twitter, so thank you for bringing it to my attention - it may have been why I end up marking these lists as unreliable!
