### ISSUE TITLE
Prigent-Malware.txt 404

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [WaLLy3K/wally3k.github.io#67]
[https://v.firebog.net/hosts/Prigent-Malware.txt](Prigent-Malware.txt) is still listed on your site but leads to a 404 error.

**Comment by Perflyst** [comment]
I do get content here, please check @Unkn0wn-MDCLXIV

**Comment by WaLLy3K** [comment]
It's possible that it may have been broken for a short period of time when @Unkn0wn-MDCLXIV experienced this issue, but it looks like it's resolved itself [as it does currently work](https://v.firebog.net/hosts/Prigent-Malware.txt) as @Perflyst has mentioned. 😄

**Comment by beerisgood** [comment]
It's offline again:

github.com (Prigent-Malware.txt)
  [✗] Status: https://github.com/WaLLy3K/wally3k.github.io/issues/Prigent-Malware.txt (406)
  [✗] List download failed: no cached list available

**Comment by WaLLy3K** [comment]
[https://v.firebog.net/hosts/Prigent-Malware.txt](https://v.firebog.net/hosts/Prigent-Malware.txt) is working for me, please ensure you have the correct URL.

**Comment by niklasea** [comment]
@WaLLy3K  It looks to be down again.

**Comment by beerisgood** [comment]
Can confirm. Got 404
@WaLLy3K
