### ISSUE TITLE
ZeuS Tracker has been discontinued on Jul 8th, 2019

### ISSUE THREAD

**Issue by pguizeline** [WaLLy3K/wally3k.github.io#68]
Hi!

The list:
https://zeustracker.abuse.ch/byebye.php?download=domainblocklist

It seem the whole site was killed on Jul 8th, 2019

**Comment by beerisgood** [comment]
Also same for
https://zeustracker.abuse.ch/blocklist.php?download=domainblocklist
which is still listed

**Comment by Perflyst** [comment]
This was already removed with 3c5d911, issue can be closed.

**Comment by WaLLy3K** [comment]
Thanks @pguizeline for bringing this up, and thanks @Perflyst for the update on this. 😄
