### ISSUE TITLE
The link to pgl.yoyo.org's list is... suboptimal

### ISSUE THREAD

**Issue by solarshado** [WaLLy3K/wally3k.github.io#71]
The current URL (https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts;showintro=0) results in a page that looks fine in-browser, but isn't actually text/plain (there's some minimal HTML wrapped around a `<pre>` tag); it sticks out like a sore thumb if you're trying to automate things. I did a little poking around and this URL (https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext) does return plain text.

**Comment by WaLLy3K** [comment]
Thank you for this input, I really appreciate it! 😊
