### ISSUE TITLE
Ticked lists

### ISSUE THREAD

**Issue by dmginc** [WaLLy3K/wally3k.github.io#72]
I could be wrong, but https://zerodot1.gitlab.io/CoinBlockerLists/hosts doesn't seem to fit the criteria for ticked lists.  It is full of nothing but legitimate links for Crypto currency related websites (obviously).  There is no reason that coinbase.com should be blocked by anything in your "ticked" list category, when there is nothing malicious about it.

**Comment by WaLLy3K** [comment]
My understanding is that it's supposed to disable browser based miners. @Zerodot1, could you confirm please?

**Comment by Obihoernchen** [comment]
It basically blocks a lot of legit bitcoin sites as well. I agree with @dmginc
Another example: bitcoin.de

**Comment by WaLLy3K** [comment]
Thank you @dmginc and @Obihoernchen, I've updated the list to point to [the in-browser list only](https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser). Please let me know if there are any issues with this!
