### ISSUE TITLE
ransomwaretracker 

### ISSUE THREAD

**Issue by hotfix** [WaLLy3K/wally3k.github.io#74]
the following lists have been discontinued
```
https://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt
https://ransomwaretracker.abuse.ch/downloads/CW_C2_DOMBL.txt
https://ransomwaretracker.abuse.ch/downloads/LY_C2_DOMBL.txt
https://ransomwaretracker.abuse.ch/downloads/TC_C2_DOMBL.txt
https://ransomwaretracker.abuse.ch/downloads/TL_C2_DOMBL.txt
```

**Comment by WaLLy3K** [comment]
Abuse.ch doesn't appear to have any other HOSTS style blocklists I can replace them with either, which is a bit of a shame.

Thank you for opening the issue so promptly after those lists have been discontinued, I sincerely appreciate it! 😊
