### ISSUE TITLE
Squidblacklist dg-malicious is empty (no longer exists?)

### ISSUE THREAD

**Issue by Ghalid** [WaLLy3K/wally3k.github.io#75]
https://www.squidblacklist.org/downloads/dg-malicious.acl, a ticked list, currently has no content.

**Comment by WaLLy3K** [comment]
I noticed this last night as well - I’m hoping it’s a temporary issue that will be resolved soon. 🙂

**Comment by frankrpi3** [comment]
Yes , it's available again!

**Comment by WaLLy3K** [comment]
A bit longer than I had hoped, but it's definitely good to see it back up again!

**Comment by beerisgood** [comment]
Sadly they offline again

>  Error 522
> Connection timed out
> 
> You -Browser: Working
> Frankfurt - Cloudflare: Working
> www.squidblacklist.org - Host: Error

**Comment by beerisgood** [comment]
Fixed with https://github.com/WaLLy3K/wally3k.github.io/commit/facf24c24d0f5407232a44a608cbe8a0e92968ba
