### ISSUE TITLE
Prigent Phishing list obsolete

### ISSUE THREAD

**Issue by frankrpi3** [WaLLy3K/wally3k.github.io#77]
Hi,

the Prigent phishing list is obsolete, because it is equal now to his malware list and therefore can be deleted. 

I have contacted him but no answer yet, but on his site there is also this notice. 

regards, Frank

**Comment by frankrpi3** [comment]
update: he contacted me and told, that he has merged both list into the malware list!

**Comment by beerisgood** [comment]
@WaLLy3K

**Comment by WaLLy3K** [comment]
Apologies for the delay in reply, and thank you *very* much for letting me know!
