### ISSUE TITLE
Possibly redundant lists

### ISSUE THREAD

**Issue by Aeriem** [WaLLy3K/wally3k.github.io#78]
Hi!

I made some research on the [ticked lists](https://v.firebog.net/hosts/lists.php?type=tick) and found some to be, I believe, redundant. I would suggest removing them, after you had a chance to check if I'm right.

The following lists are already defaults of Pi-hole.
```
https://mirror1.malwaredomains.com/files/justdomains
https://hosts-file.net/ad_servers.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
```
~~These are not actual lists but copies made by StevenBlack which are consolidated with others in his hosts list, and should be replaced by it. Furthermore, his list is already a default one in Pi-hole.~~
```
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/KADhosts/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/UncheckyAds/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Risk/hosts
```
~~These lists are already part of StevenBlack's hosts list, and therefore included in Pi-hole.~~
```
https://adaway.org/hosts.txt
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
https://www.malwaredomainlist.com/hostslist/hosts.txt
```
These two haven't been updated in years, making them really obsolete. Dates of last update and links to the hosting repositories are included at the end of each link.
```
https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt (Apr 25, 2014: https://bitbucket.org/ethanr/dns-blacklists/src/master/bad_lists/Mandiant_APT1_Report_Appendix_D.txt)
https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts (Aug 4, 2016: https://github.com/ReddestDream/reddestdream.github.io/blob/master/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts)
```
I'm not completely sure of this one's redundancy. The immortal_domains.txt list **seems** to be included in the justdomains one, and justdomains is included in Pi-hole. [This other official mirror](https://mirror1.malwaredomains.com/) (as listed [here](http://www.malwaredomains.com/?page_id=29)) does not point to immortal_domains.txt as something that should be used, so I'm inclined to think that it is a resource of the repository and we should instead use the justdomains list as they recommend. I'd like to hear your opinion about this.
```
https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
```
Thank you for sharing your Big Blocklist Collection!

**Comment by Aeriem** [comment]
I didn't rigorously check the rest of the collection, but I happened to notice two more redundant lists.

`http://winhelp2002.mvps.org/hosts.txt` is included in StevenBlack's hosts.
`http://sysctl.org/cameleon/hosts` is a Pi-hole default.

**Comment by frankrpi3** [comment]
Hi,
this redundancy was also discussed here:
https://github.com/WaLLy3K/wally3k.github.io/issues/11

Meanwhile I only use Wally‘s ticked lists and pi-hole works really good with only a few whitelisted domains.

The developers of pi-hole put this list at the beginning of the project as a good default list to start with.

**Comment by XhmikosR** [comment]
@WaLLy3K maybe I also suggest that you have the default Pi-hole lists at the top in https://v.firebog.net/hosts/lists.php?type=tick ?

**Comment by Aeriem** [comment]
@frankrpi3: Thanks for the link, @WaLLy3K's position is understandable, he explains it on the Firebog's homepage and I actually agree with him. The only reason I thought this was still worth mentioning is because StevenBlack's list is a Pi-hole default. Else I wouldn't have brought it up. With that in mind, I will correct my original post.

**Comment by frankrpi3** [comment]
There is nothing to correct. The intention of my old post also was to clarify the double content.
Also i agree in removing those old not curated lists.

**Comment by WaLLy3K** [comment]
Since you've crossed some entries out, I'll move past them since (I presume) you're okay with the answers received above! 🙂

> The following lists are already defaults of Pi-hole.
> 
> ```
> https://mirror1.malwaredomains.com/files/justdomains
> https://hosts-file.net/ad_servers.txt
> https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
> ```

One of the expected use-cases of my list is to completely overwrite the existing adlist file, which I replace Steven Black's consolidated list with their original sources.

> These two haven't been updated in years, making them really obsolete. Dates of last update and links to the hosting repositories are included at the end of each link.
> 
> ```
> https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt (Apr 25, 2014: https://bitbucket.org/ethanr/dns-blacklists/src/master/bad_lists/Mandiant_APT1_Report_Appendix_D.txt)
> https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts (Aug 4, 2016: https://github.com/ReddestDream/reddestdream.github.io/blob/master/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts)
> ```
The Mandiant's report on the so-called China Cyber Espionage Unit known as APT1 is a static list that's not expected to change. Feel free to [search up more about this](https://duckduckgo.com/?q=Mandiant+APT1+Report&ia=web).

ReddestDream doesn't have time to maintain their blocklist any more, and taking the time to query roughly 20 domains throughout that list shows that all that I checked were in at least one other list. I think I can safely remove it.

> I'm not completely sure of this one's redundancy. The immortal_domains.txt list **seems** to be included in the justdomains one, and justdomains is included in Pi-hole. [This other official mirror](https://mirror1.malwaredomains.com/) (as listed [here](http://www.malwaredomains.com/?page_id=29)) does not point to immortal_domains.txt as something that should be used, so I'm inclined to think that it is a resource of the repository and we should instead use the justdomains list as they recommend. I'd like to hear your opinion about this.
> 
> ```
> https://mirror.cedia.org.ec/malwaredomains/immortal_domains.txt
> ```

Doing a query of `iloveeu.es` (one of the random domains I picked out) against other blocklists shows it's not found in any other list. I'm inclined to keep this list mostly for this fact alone, but also because there wouldn't be any harm (read: false positives) in keeping it.

> Thank you for sharing your Big Blocklist Collection!

Thanks for contributing, and sharing your appreciation! 💚

**Comment by WaLLy3K** [comment]
If there's anything further to discuss on this, people are more than welcome to re-open the ticket! 🙂

**Comment by Aeriem** [comment]
Thank you for taking the time to review this issue and giving your thoughts on the matter, I really appreciate it. 😄
