### ISSUE TITLE
"hpHosts" trustable?

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#79]
If you wan't post a false positive to this guys and visit their [site](https://hosts-file.net/?s=Help#submission)  you got the following:

> Q: How do I submit removal/addition/modification requests?
>
> A. Previously, this could be done via the hpHosts forums. However, this was **recently maliciously compromised**, and thus I disabled it. Because of this, the only way to submit removal/addition/modification requests at present, is to send me an e-mail. 
>

So if you click on[ Contact Us](https://forums.malwarebytes.com/forum/123-website-blocking/) you get redirect to that forum. Is it still compromised? How knows?

Okay, i then try to directly contact the guy and under [Need help?](https://hosts-file.net/?s=Help) on "contact me" i got redirected to this [non-existing](http://mysteryfcm.co.uk/?mode=Contact) domain.

So should we realy trust these hpHosts guys? They don't even can maintain their own site.

I come to this because i wan't submit the false positive "telecommand.telemetry.microsoft.com" but looks like i can't.

**Comment by beerisgood** [comment]
@WaLLy3K

**Comment by Aeriem** [comment]
The "Contact Us" button sends you to the Malwarebytes forums, not the hpHosts forums that were compromised, so I think you can post there safely.

While the website could use an update to correct this dead link and some minor other stuff, the actual hosts files have a good reputation.

**Comment by WaLLy3K** [comment]
I completely concur with @Aeriem. In the seven or eight years I've run their lists, I've found extremely few false positives and appear to keep on top of their whitelisting requests.

Can't judge the quality of a blocklist by their website! 😂
