### ISSUE TITLE
Replace https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts with original

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#81]
Please replace https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts with the original source:
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts

You can verify that on https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant

**Comment by frankrpi3** [comment]
Hi,

maybe these urls can be changed to from:

https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.2o7Net/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Risk/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/add.Spam/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/KADhosts/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/data/UncheckyAds/hosts

to:

https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts_without_controversies.txt
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts

**Comment by Aeriem** [comment]
This would be a good idea. :)

**Comment by WaLLy3K** [comment]
Fantastic job @frankrpi3, that was extremely helpful!

Cheers for @beerisgood for bringing the issue to my attention - I'd much rather use an original source over a mirror! 🙂
