### ISSUE TITLE
Worldoftanks.eu domains blocked in Airelle-trc list

### ISSUE THREAD

**Issue by Geraner** [WaLLy3K/wally3k.github.io#82]
The following two domain names are been recently added to the Airelle-trc list. (Category Tracking & Telemetry Lists).
join.worldoftanks.eu
worldoftanks.eu

This must be a false postive! Please check and change!
Links are connected to the game World of Tanks.

Best regards
Geraner

**Comment by frankrpi3** [comment]
Both Airelle lists are marked with a cross, means that they can contain many false positives. Best practice is to use only the ticked lists. 
Also if you want to have to correct this, you have to contact the creator of the list.

**Comment by WaLLy3K** [comment]
@frankrpi3 is absolutely correct. Airelle has consistently shown that while generally responsive to whitelisting requests, the quality of the content of their list leaves a lot to be desired - as evidenced by the time `s3.amazonaws.com` was blocked.

I would strongly urge you to remove those lists to continue to enjoy a browsing experience with minimal false positives. :)
