### ISSUE TITLE
squidblacklist.org is down

### ISSUE THREAD

**Issue by ricktendo** [WaLLy3K/wally3k.github.io#84]
Seems to be down for some days now

https://downforeveryoneorjustme.com/squidblacklist.org

**Comment by WaLLy3K** [comment]
Combined with issue #75 as well as [the Facebook announcement of the death of SBL's owner](https://www.facebook.com/squidblacklist) mid last year, it's now definitely time to sunset this list. It's been a good run!

Thanks @ricktendo, @Ghalid and @beerisgood!
