### ISSUE TITLE
CAMELEON hosts file is deprecated

### ISSUE THREAD

**Issue by Aeriem** [WaLLy3K/wally3k.github.io#85]
Guess who's back at it again, hehe?

On the [CAMELEON website](https://sysctl.org/cameleon/), the hosts files are listed as deprecated, and no longer updated. I downloaded the UNIX format hosts file to check: `# Last updated : 2018-03-17`.
I know this list is quite reputable, but I still wanted to let you know, especially with the CNAME blocking change that's coming in Pi-hole 5.0.

**Comment by WaLLy3K** [comment]
Thanks @Aeriem! I think not being updated for two years is a reasonable point in which a list should be removed.

Apologies for how long it's taken to investigate and action this!

**Comment by Aeriem** [comment]
You're welcome and no worries! 😃
