### ISSUE TITLE
w3tech_hostfile is 404'ing

### ISSUE THREAD

**Issue by XhmikosR** [WaLLy3K/wally3k.github.io#86]
Kees1958's Ad/Tracking Blocklist: https://raw.githubusercontent.com/Kees1958/WS3_annual_most_used_survey_blocklist/master/w3tech_hostfile.txt

Apparently they renamed the file and changed its syntax https://github.com/Kees1958/WS3_annual_most_used_survey_blocklist/blob/master/Small_but_effective_blocklist.txt

**Comment by beerisgood** [comment]
Only the (removed) w3tech_hostfile.txt was designed for uMatrix & PiHole.

The Small_but_effective_blocklist.txt is for Adblocker like uBlock Origin

**Comment by WaLLy3K** [comment]
Thank you @XhmikosR!
