### ISSUE TITLE
MVPS HOSTS now available through HTTPS

### ISSUE THREAD

**Issue by Aeriem** [WaLLy3K/wally3k.github.io#87]
HTTPS URL: https://winhelp2002.mvps.org/hosts.txt
That was the very last HTTP list on the Firebog! Congrats!

**Comment by beerisgood** [comment]
Any false positives with that list known?

**Comment by Aeriem** [comment]
Not that I am aware of, but I'm no expert on the matter.
Maybe @WaLLy3K can tell us why it isn't a ticked list?

**Comment by WaLLy3K** [comment]
I'm not aware of anything in the ways of false positives for this list, however I've always erred away from making *any* general/generic/suspicious category blocklist a ticklist; favouring those who have a specific category such as advertising, tracking and malware.

I'm happy to revisit this line of thinking, but that *has* always been my reasoning! 🙂

**Comment by Aeriem** [comment]
That's a good rule of thumb. However, this list is included in StevenBlack's and has a good reputation.
I would I think it's probably safe to tick it, but ultimately, the decision is yours. Maybe you could make an exception based on the low false positives count. Maybe you could adapt your rule, but I can't really come up with a simple one to suggest. However, I believe that HTTPS connection, good reputation online (based on multiple reliable sources), low false positives count, and maintainer(s) responsiveness are the elements you should base your decision on.

**Comment by XhmikosR** [comment]
@WaLLy3K you can close this one
