### ISSUE TITLE
Kowabit Host - Many Genuine Domains Blocked - Need to Avoid Usage

### ISSUE THREAD

**Issue by desmonk** [WaLLy3K/wally3k.github.io#88]
Don't know if this was intentional or not but this host file apparently blocks many domains directly. Can anyone have something on this?

https://v.firebog.net/hosts/Kowabit.txt

![Kowabit Hosts](https://user-images.githubusercontent.com/55331939/75346691-2e668c80-5897-11ea-9b81-31ae24147437.PNG)

![Kowabit List](https://user-images.githubusercontent.com/55331939/75346926-9c12b880-5897-11ea-9d9b-f0fb7970c41b.png)

**Comment by frankrpi3** [comment]
That’s the reason, why Wally put a cross before that link!
See „ Before starting, here are some reading points:...“

**Comment by WaLLy3K** [comment]
It’s marked with a cross to show users of the blocklist collection (as well as those who consolidate lists) that it’s of very poor quality, and that it’s to be avoided. 🙂

**Comment by desmonk** [comment]
Been using all the list for over years now and only reported this as began happening in the past few days only. So something was changed on the list recently which actually broke many websites.

Glad to hear from you too! :)
