### ISSUE TITLE
IDs for lists

### ISSUE THREAD

**Issue by ohreally** [WaLLy3K/wally3k.github.io#9]
Hi,

Thanks for this list.
Could you please give an ID to each &lt;ul class="bdUrlList"&gt;-block? Something like &lt;ul id="listSuspicious" class="bdUrlList"&gt; would be perfect. This would allow me to automate the retrieval and processing of the lists.
Obviously I would be happy to share my script when I finish it.

Thanks,
  Rob

P.s.:
Yes, I could have forked, changed and sent a pull request. But I think it's less work this way.

**Comment by WaLLy3K** [comment]
Thanks for the suggestion! Hopefully the change in the last commit covers what you're asking for. 😄 

If not, let me know!

**Comment by ohreally** [comment]
Thank you very much.

And, as promised, I'm sharing my script: https://github.com/ohreally/w3k2oh
