### ISSUE TITLE
Prigent Malware returns 404

### ISSUE THREAD

**Issue by XhmikosR** [WaLLy3K/wally3k.github.io#90]
@WaLLy3K it seems https://v.firebog.net/hosts/Prigent-Malware.txt returns 404 for some days now. Is the list removed on purpose?

**Comment by beerisgood** [comment]
See https://github.com/WaLLy3K/wally3k.github.io/issues/67

**Comment by WaLLy3K** [comment]
Cloudflare seemingly decided to cache those lists during a brief moment when they weren't available, so I've cleared CF's cache and they're back.

Thanks to `@dominikconrads ` notifying me on Twitter.

**Comment by beerisgood** [comment]
> 
> Thanks to `@dominikconrads ` notifying me on Twitter.

You should enable GitHub notifications ;)

**Comment by WaLLy3K** [comment]
> > Thanks to `@dominikconrads ` notifying me on Twitter.
> 
> You should enable GitHub notifications ;)

I recently changed to [GitHub for mobile](https://github.com/mobile/) and notifications are definitely enabled. The ability to reliably get GH notifications is a real pain in my side :(

**Comment by beerisgood** [comment]
> > > Thanks to `@dominikconrads ` notifying me on Twitter.
> > 
> > 
> > You should enable GitHub notifications ;)
> 
> I recently changed to [GitHub for mobile](https://github.com/mobile/) and notifications are definitely enabled. The ability to reliably get GH notifications is a real pain in my side :(

I get emails which is (for me) much more convenient then using a own app but if that works for you, ok

**Comment by WaLLy3K** [comment]
Emails are definitely more inconvenient for me because the inbox I send them to isn't checked regularly whereas a push notification can be glanced at quickly. I'm currently sending email notifications through Pushover, and while it's hacky, means that I saw your response as soon as you posted it :)
