### ISSUE TITLE
Remove hosts-file.net lists

### ISSUE THREAD

**Issue by XhmikosR** [WaLLy3K/wally3k.github.io#91]
* https://github.com/pi-hole/pi-hole/pull/3236
* https://github.com/uBlockOrigin/uBlock-issues/issues/971
* https://forums.malwarebytes.com/topic/257401-inquiry-regarding-automated-processing-of-hosts-files/
* https://www.reddit.com/r/pihole/comments/fsg11e/hostsfilenet/

**Comment by WaLLy3K** [comment]
I guess they just can't see how to make money off of it, by the sounds of it!

Not sure if my mirrored copies will auto-erase themselves over time, but here's the most recent updates:
https://v.firebog.net/hosts/HPHosts-ads.txt
https://v.firebog.net/hosts/HPHosts-emd.txt
https://v.firebog.net/hosts/HPHosts-exp.txt
https://v.firebog.net/hosts/HPHosts-psh.txt

I'll look into changing the URL's on my collection as soon as possible, as I'm not in a position to do it where I am right now :)

**Comment by XhmikosR** [comment]
Oh, I didn't know you had a copy of the lists! Do you happen to have their other lists too?

**Comment by XhmikosR** [comment]
BTW it seems your copies have `localhost` in it at the top

**Comment by WaLLy3K** [comment]
HPHosts, no, just these IIRC.

**Comment by XhmikosR** [comment]
Thanks!

Personally I was using these lists from them:

```
https://hosts-file.net/ad_servers.txt
https://hosts-file.net/emd.txt
https://hosts-file.net/exp.txt
https://hosts-file.net/fsa.txt
https://hosts-file.net/grm.txt
https://hosts-file.net/hjk.txt
https://hosts-file.net/mmt.txt
https://hosts-file.net/psh.txt
```

**Comment by tmcqueen-materials** [comment]
I am not in a position to host them, but here are some of the latest copies if useful.
[HostsAdServers.zip](https://github.com/WaLLy3K/wally3k.github.io/files/4421054/HostsAdServers.zip)
[Hostsemd.zip](https://github.com/WaLLy3K/wally3k.github.io/files/4421055/Hostsemd.zip)
[Hostsexp.zip](https://github.com/WaLLy3K/wally3k.github.io/files/4421056/Hostsexp.zip)
[Hostsfsa.zip](https://github.com/WaLLy3K/wally3k.github.io/files/4421057/Hostsfsa.zip)
[Hostsgrm.zip](https://github.com/WaLLy3K/wally3k.github.io/files/4421058/Hostsgrm.zip)
[Hostsmmt.zip](https://github.com/WaLLy3K/wally3k.github.io/files/4421059/Hostsmmt.zip)
[Hostspha.zip](https://github.com/WaLLy3K/wally3k.github.io/files/4421060/Hostspha.zip)
[Hostspsh.zip](https://github.com/WaLLy3K/wally3k.github.io/files/4421061/Hostspsh.zip)

**Comment by dnmTX** [comment]
@tmcqueen-materials thanks.Keep the links alive please,at least for a while 👍

**Comment by derekslenk** [comment]
How much  bandwidth is needed to host them?

**Comment by XhmikosR** [comment]
We can just host them on a GitHub repo. It's just that I personally don't have any copies and also this should be cooperated with @WaLLy3K so that the new URLs are added to his site.

**Comment by derekslenk** [comment]
Was just offering if we need it in the meantime. I do not want to take over @WaLLy3K's job

**Comment by XhmikosR** [comment]
I know, I didn't mean it that way 🙂 Just saying that we should do this right.

**Comment by kravietz** [comment]
Unmanaged blocklist is worse than no blocklist in long term. If Malwarebytes is unable to maintain them it's perfectly undestandable, I guess it's time to find a project that _does_ actively maintain them and crowdfund it to provide sustainable motivation to keep it this way.

**Comment by XhmikosR** [comment]
@WaLLy3K friendly ping 🙂

If you cannot host them, you should remove them from the website and I'm sure someone will offer to host them somewhere. Although, personally, I'd prefer it if the lists were in this repo + your site.

**Comment by WaLLy3K** [comment]
> Unmanaged blocklist is worse than no blocklist in long term. If Malwarebytes is unable to maintain them it's perfectly undestandable, I guess it's time to find a project that _does_ actively maintain them and crowdfund it to provide sustainable motivation to keep it this way.

Given the daunting scale of these lists (and also the sheer amount of false positives I've seen added to these in in the last eight or so years of using them), it's not going to be a case of ~set and forget~ host and forget. As much as I don't want to, I think I'm best off to remove these for now because I'd rather not be in the position of dealing with whitelist requests for a handful of reasons.

I've archived the lists that @tmcqueen-materials has thankfully provided [over here](https://v.firebog.net/hosts/static/HPHosts/), but I don't intend on using them for the time being. The bandwidth for them shouldn't be an issue as Cloudflare handles 99% of the bandwidth for me on their free tier.

Thanks all! :)

**Comment by spirillen** [comment]
I'm about to posts the Cleaned-up version in this bucket <https://bitbucket.org/expiredsources/hosts-file.net/src/master/> Alternate location: https://www.mypdns.org/source/HPhosts/

These would be cleaned with @funilrys [PyFunceble](https://github.com/funilrys/PyFunceble) over `--dns 1.1.1.1`

**Comment by vuxat** [comment]
I downloaded the Hijack List from host-file.net from my pi-hole
https://gist.github.com/vuxat/f25149898451efc6a2723af7c6643f82#file-hosts-file-net_hjk-txt

**Comment by vuxat** [comment]
I downloaded the original hjk.txt file from my pihole:
https://gist.githubusercontent.com/vuxat/f25149898451efc6a2723af7c6643f82/raw/5985279ee61a7a77d4f5a5163460177b6a8b62e2/hosts-file.net_hjk.txt

**Comment by VR51** [comment]
I can sorta help with the backup file. I'm the originator of Host-Flash, a Linux hosts file manager script. This script builds and updates the hosts file from a range of selectable sources. I have a hosts file build from April 2019 that contains the old lists that were available from hosts-file.net. Here is the sorta part: the April 2019 build is mixed in with lists from multiple sources and there is no way to discern which hosts came from which source. If you want to peruse/use the file its zip can be obtained here https://github.com/VR51/host-flash/tree/master/assets.
