### ISSUE TITLE
Prigent-Malware blocks bitbucket.org

### ISSUE THREAD

**Issue by XhmikosR** [WaLLy3K/wally3k.github.io#95]
@WaLLy3K I reported this to Fabrice and he fixed already fixed it, but it would be nice if you could update your [list](https://v.firebog.net/hosts/Prigent-Malware.txt) to prevent breakage since bitbucket.org is quite popular.

BTW I was wondering how often are your lists updated? Do you have a cron job? If so can you share a little bit more info about when it runs?

Thanks!

**Comment by WaLLy3K** [comment]
As per [this comment](https://github.com/WaLLy3K/wally3k.github.io/issues/94#issuecomment-612349425), it used to be each Sunday morning that the cron job would fire, but is now every three days - [`0 0 * * */3`](https://crontab.guru/#0_0_*_*_*/3).

I've attempted a manual reupdate for `Prigent-Malware.txt`, but `bitbucket.org` still exists even after clearing CloudFlare cache. I'll have to try again later and see how it goes.

**Comment by XhmikosR** [comment]
@WaLLy3K maybe you could add this info somewhere so that it's clearer? 

Thanks for the info BTW!

**Comment by WaLLy3K** [comment]
The info is [out there, but a bit hidden](https://v.firebog.net/hosts/) as most people don't want to concern themselves with specifics like that :)

**Comment by XhmikosR** [comment]
To be fair, even I didn't notice that and I was concerned about the specifics :)

So, maybe you could add this info or a link in the repo README? And maybe like to it in your main page? If there's a link I personally can't see it.

**Comment by XhmikosR** [comment]
The issue with `bitbucket.org` being blocked in now fixed.

@WaLLy3K I still think you should consider the above suggestion when you have some time; it will make things more transparent IMHO. 🙂
