### ISSUE TITLE
Fork for Kees1958's Ad/Tracking Blocklist 

### ISSUE THREAD

**Issue by nefty1029** [WaLLy3K/wally3k.github.io#97]
I found a fork for Kees1958's Ad/Tracking Blocklist (now called the Top 500 list) by InnoScorpio.
I remember the original list by Kees1958 was removed from the ticked filterlist a few months ago due to the removal of the hosts file. This fork comes with both hosts and domain files.

https://github.com/InnoScorpio/W3C_annual_most_used_survey_blocklist

**Comment by WaLLy3K** [comment]
Many of the domains here are shared with other lists, but there's still enough that aren't on any list. So sure, I can add this one in! :)

**Comment by beerisgood** [comment]
Both the [list](https://raw.githubusercontent.com/InnoScorpio/W3C_annual_most_used_survey_blocklist/master/Top500_Domains.txt) and the [GitHub site](https://github.com/InnoScorpio/W3C_annual_most_used_survey_blocklist) doesn't exist anymore

@nefty1029 
@WaLLy3K

**Comment by WaLLy3K** [comment]
Conversation [carries over to this ticket](https://github.com/WaLLy3K/wally3k.github.io/issues/101).
