### ISSUE TITLE
Youtube History Being Blocked by Easyprivacy.txt List.

### ISSUE THREAD

**Issue by tutt412** [WaLLy3K/wally3k.github.io#98]
Found a false positive in EasyPrivacy.txt. 

s.youtube.com – used for Youtube history.

The rest of the lists you have compiled have worked great with no other false positives. Thank you for compiling them!!

**Comment by WaLLy3K** [comment]
I'd look into whether you could submit your request upstream to the [EasyPrivacy repo](https://github.com/easylist/easylist/issues). If that gets shot down, I *only then* (depending on what the devs say in response) would be willing to consider writing an exception in my parser to ignore that domain.

Lemme know how you go @tutt412, and sorry for the delay in reply!
